package com.ailk.openbilling.persistence.jd.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="JD",name="IMS_PORTABILITY_HIS")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"userId","inRegion","outRegion","regionCode","validDate","dealDate"})
public class ImsPortabilityHis extends DataObject{


	@Id
	@Column(name="USER_ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="IN_REGION",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="inRegion")
	private Integer inRegion;

	@Column(name="OUT_REGION",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="outRegion")
	private Integer outRegion;

	@Column(name="REGION_CODE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="regionCode")
	private Integer regionCode;

	/**
	 * 处理月份 
eg:201312
	 */
	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="DEAL_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="dealDate")
	private Date dealDate;

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setInRegion(Integer obj){
		this.inRegion = obj;
	}

	public Integer getInRegion(){
		return inRegion;
	}

	public void setOutRegion(Integer obj){
		this.outRegion = obj;
	}

	public Integer getOutRegion(){
		return outRegion;
	}

	public void setRegionCode(Integer obj){
		this.regionCode = obj;
	}

	public Integer getRegionCode(){
		return regionCode;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setDealDate(Date obj){
		this.dealDate = obj;
	}

	public Date getDealDate(){
		return dealDate;
	}

	public ImsPortabilityHis(){
	}

	public ImsPortabilityHis(Long userId){
		this.userId = userId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		ImsPortabilityHis rhs=(ImsPortabilityHis)rhs0;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(userId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{userId,inRegion,outRegion,regionCode,validDate,dealDate}
}