package com.ailk.openbilling.persistence.jd.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="JD",name="IMS_RES_MONITOR")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"resourceId","serviceId","monitorCondId","monitorType","operType","validDate","expireDate","soNbr","createDate","sts","dealDate","remark","sourceId"})
public class ImsResMonitor extends DataObject{


	/**
	 * 资源编号
	 */
	@Id
	@Column(name="RESOURCE_ID",precision=15,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resourceId")
	private long resourceId;

	/**
	 * 服务标识,监控的业务大类， 目前存在语音，短信，GPRS等几种业务
	 */
	@Column(name="SERVICE_ID",precision=9,columnDefinition="NUMBER")
	@XmlElement(name="serviceId")
	private Integer serviceId;

	/**
	 * 欠控业务,监控业务条件表达式ID， 目前高危系统默认为0
	 */
	@Column(name="MONITOR_COND_ID",precision=9,columnDefinition="NUMBER")
	@XmlElement(name="monitorCondId")
	private Integer monitorCondId;

	/**
	 * 0: 离线业务, 1:欠控业务; 2:在线业务 ， 目前高危系统默认为1
	 */
	@Column(name="MONITOR_TYPE",precision=2,columnDefinition="NUMBER")
	@XmlElement(name="monitorType")
	private Integer monitorType;

	/**
	 * 处理类型:1:迁入2：迁出
	 */
	@Column(name="OPER_TYPE",precision=2,columnDefinition="NUMBER")
	@XmlElement(name="operType")
	private Integer operType;

	/**
	 * 生效时间
	 */
	@Id
	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="SO_NBR",precision=15,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	/**
	 * 处理状态
	 */
	@Column(name="STS",precision=2,columnDefinition="NUMBER")
	@XmlElement(name="sts")
	private Integer sts;

	/**
	 * 处理时间
	 */
	@Column(name="DEAL_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealDate")
	private Date dealDate;

	@Column(name="REMARK",columnDefinition="Varchar",length=256)
	@XmlElement(name="remark")
	private String remark;

	/**
	 * 数据来源
	 */
	@Column(name="SOURCE_ID",precision=2,columnDefinition="NUMBER")
	@XmlElement(name="sourceId")
	private Integer sourceId;

	public void setResourceId(long obj){
		this.resourceId = obj;
	}

	public long getResourceId(){
		return resourceId;
	}

	public void setServiceId(Integer obj){
		this.serviceId = obj;
	}

	public Integer getServiceId(){
		return serviceId;
	}

	public void setMonitorCondId(Integer obj){
		this.monitorCondId = obj;
	}

	public Integer getMonitorCondId(){
		return monitorCondId;
	}

	public void setMonitorType(Integer obj){
		this.monitorType = obj;
	}

	public Integer getMonitorType(){
		return monitorType;
	}

	public void setOperType(Integer obj){
		this.operType = obj;
	}

	public Integer getOperType(){
		return operType;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setSts(Integer obj){
		this.sts = obj;
	}

	public Integer getSts(){
		return sts;
	}

	public void setDealDate(Date obj){
		this.dealDate = obj;
	}

	public Date getDealDate(){
		return dealDate;
	}

	public void setRemark(String obj){
		this.remark = obj;
	}

	public String getRemark(){
		return remark;
	}

	public void setSourceId(Integer obj){
		this.sourceId = obj;
	}

	public Integer getSourceId(){
		return sourceId;
	}

	public ImsResMonitor(){
	}

	public ImsResMonitor(long resourceId,Date validDate){
		this.resourceId = resourceId;
		this.validDate = validDate;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		ImsResMonitor rhs=(ImsResMonitor)rhs0;
		if(!ObjectUtils.equals(resourceId, rhs.resourceId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(resourceId)
		.append(validDate)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{resourceId,serviceId,monitorCondId,monitorType,operType,validDate,expireDate,soNbr,createDate,sts,dealDate,remark,sourceId}
}