package com.ailk.openbilling.persistence.jd.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */

@Entity
@Table(schema="JD",name="IMS_USER_CONFIRM")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"userId","acctId","phoneId","spCode","operatorCode","billFlag","thirdMsisdn","billProp","regionCode","startTime","alarmType","alarmPara","alarmSource","totalFee","updateDate","sequenceNo","serviceCode","remark","soDate","sts","soNbr","custId","reservice1"})
public class ImsUserConfirm extends DataObject{


	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="PHONE_ID",columnDefinition="Varchar",length=32,nullable=false)
	@XmlElement(name="phoneId")
	private String phoneId;

	@Column(name="SP_CODE",columnDefinition="Varchar",length=32,nullable=false)
	@XmlElement(name="spCode")
	private String spCode;

	@Column(name="OPERATOR_CODE",columnDefinition="Varchar",length=32,nullable=false)
	@XmlElement(name="operatorCode")
	private String operatorCode;

	@Column(name="BILL_FLAG",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="billFlag")
	private Integer billFlag;

	@Column(name="THIRD_MSISDN",columnDefinition="Varchar",length=15,nullable=false)
	@XmlElement(name="thirdMsisdn")
	private String thirdMsisdn;

	@Column(name="BILL_PROP",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="billProp")
	private Integer billProp;

	@Column(name="REGION_CODE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="regionCode")
	private Integer regionCode;

	@Column(name="START_TIME",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="startTime")
	private Date startTime;

	@Column(name="ALARM_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="alarmType")
	private Integer alarmType;

	@Column(name="ALARM_PARA",columnDefinition="Varchar",length=256,nullable=false)
	@XmlElement(name="alarmPara")
	private String alarmPara;

	@Column(name="ALARM_SOURCE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="alarmSource")
	private Integer alarmSource;

	@Column(name="TOTAL_FEE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="totalFee")
	private Long totalFee;

	@Column(name="UPDATE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="updateDate")
	private Date updateDate;

	@Column(name="SEQUENCE_NO",columnDefinition="Varchar",length=32,nullable=false)
	@XmlElement(name="sequenceNo")
	private String sequenceNo;

	@Column(name="SERVICE_CODE",columnDefinition="Varchar",length=64,nullable=false)
	@XmlElement(name="serviceCode")
	private String serviceCode;

	@Column(name="REMARK",columnDefinition="Varchar",length=256,nullable=false)
	@XmlElement(name="remark")
	private String remark;

	@Column(name="SO_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="soDate")
	private Date soDate;

	@Column(name="STS",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="sts")
	private Integer sts;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="soNbr")
	private Long soNbr;
	
	@Column(name="CUST_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="custId")
	private Long custId;
    
	@Column(name="RESERVICE1",columnDefinition="Varchar",length=32,nullable=false)
	@XmlElement(name="reservice1")
	private String reservice1;

	public String getReservice1() {
		return reservice1;
	}

	public void setReservice1(String reservice1) {
		this.reservice1 = reservice1;
	}

	public Long getCustId() {
		return custId;
	}

	public void setCustId(Long custId) {
		this.custId = custId;
	}

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setPhoneId(String obj){
		this.phoneId = obj;
	}

	public String getPhoneId(){
		return phoneId;
	}

	public void setSpCode(String obj){
		this.spCode = obj;
	}

	public String getSpCode(){
		return spCode;
	}

	public void setOperatorCode(String obj){
		this.operatorCode = obj;
	}

	public String getOperatorCode(){
		return operatorCode;
	}

	public void setBillFlag(Integer obj){
		this.billFlag = obj;
	}

	public Integer getBillFlag(){
		return billFlag;
	}

	public void setThirdMsisdn(String obj){
		this.thirdMsisdn = obj;
	}

	public String getThirdMsisdn(){
		return thirdMsisdn;
	}

	public void setBillProp(Integer obj){
		this.billProp = obj;
	}

	public Integer getBillProp(){
		return billProp;
	}

	public void setRegionCode(Integer obj){
		this.regionCode = obj;
	}

	public Integer getRegionCode(){
		return regionCode;
	}

	public void setStartTime(Date obj){
		this.startTime = obj;
	}

	public Date getStartTime(){
		return startTime;
	}

	public void setAlarmType(Integer obj){
		this.alarmType = obj;
	}

	public Integer getAlarmType(){
		return alarmType;
	}

	public void setAlarmPara(String obj){
		this.alarmPara = obj;
	}

	public String getAlarmPara(){
		return alarmPara;
	}

	public void setAlarmSource(Integer obj){
		this.alarmSource = obj;
	}

	public Integer getAlarmSource(){
		return alarmSource;
	}

	public void setTotalFee(Long obj){
		this.totalFee = obj;
	}

	public Long getTotalFee(){
		return totalFee;
	}

	public void setUpdateDate(Date obj){
		this.updateDate = obj;
	}

	public Date getUpdateDate(){
		return updateDate;
	}

	public void setSequenceNo(String obj){
		this.sequenceNo = obj;
	}

	public String getSequenceNo(){
		return sequenceNo;
	}

	public void setServiceCode(String obj){
		this.serviceCode = obj;
	}

	public String getServiceCode(){
		return serviceCode;
	}

	public void setRemark(String obj){
		this.remark = obj;
	}

	public String getRemark(){
		return remark;
	}

	public void setSoDate(Date obj){
		this.soDate = obj;
	}

	public Date getSoDate(){
		return soDate;
	}

	public void setSts(Integer obj){
		this.sts = obj;
	}

	public Integer getSts(){
		return sts;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public ImsUserConfirm(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		ImsUserConfirm rhs=(ImsUserConfirm)rhs0;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(phoneId, rhs.phoneId)) return false;
		if(!ObjectUtils.equals(spCode, rhs.spCode)) return false;
		if(!ObjectUtils.equals(operatorCode, rhs.operatorCode)) return false;
		if(!ObjectUtils.equals(billFlag, rhs.billFlag)) return false;
		if(!ObjectUtils.equals(thirdMsisdn, rhs.thirdMsisdn)) return false;
		if(!ObjectUtils.equals(billProp, rhs.billProp)) return false;
		if(!ObjectUtils.equals(regionCode, rhs.regionCode)) return false;
		if(!ObjectUtils.equals(startTime, rhs.startTime)) return false;
		if(!ObjectUtils.equals(alarmType, rhs.alarmType)) return false;
		if(!ObjectUtils.equals(alarmPara, rhs.alarmPara)) return false;
		if(!ObjectUtils.equals(alarmSource, rhs.alarmSource)) return false;
		if(!ObjectUtils.equals(totalFee, rhs.totalFee)) return false;
		if(!ObjectUtils.equals(updateDate, rhs.updateDate)) return false;
		if(!ObjectUtils.equals(sequenceNo, rhs.sequenceNo)) return false;
		if(!ObjectUtils.equals(serviceCode, rhs.serviceCode)) return false;
		if(!ObjectUtils.equals(remark, rhs.remark)) return false;
		if(!ObjectUtils.equals(soDate, rhs.soDate)) return false;
		if(!ObjectUtils.equals(sts, rhs.sts)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(custId, rhs.custId)) return false;
		if(!ObjectUtils.equals(reservice1, rhs.reservice1)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(userId)
		.append(acctId)
		.append(phoneId)
		.append(spCode)
		.append(operatorCode)
		.append(billFlag)
		.append(thirdMsisdn)
		.append(billProp)
		.append(regionCode)
		.append(startTime)
		.append(alarmType)
		.append(alarmPara)
		.append(alarmSource)
		.append(totalFee)
		.append(updateDate)
		.append(sequenceNo)
		.append(serviceCode)
		.append(remark)
		.append(soDate)
		.append(sts)
		.append(soNbr)
		.append(custId)
		.append(reservice1)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{userId,acctId,phoneId,spCode,operatorCode,billFlag,thirdMsisdn,billProp,regionCode,startTime,alarmType,alarmPara,alarmSource,totalFee,updateDate,sequenceNo,serviceCode,remark,soDate,sts,soNbr,custId,reservice1}
}