package com.ailk.openbilling.persistence.acct.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="AD",name="CA_RC_DATA")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"acctId","createDate","dealDate","sts","sourceType","result"})
public class CaRcData extends DataObject{


	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	@Column(name="DEAL_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealDate")
	private Date dealDate;

	@Column(name="STS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="sts")
	private Integer sts;

	@Column(name="SOURCE_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="sourceType")
	private Integer sourceType;

	@Column(name="RESULT",columnDefinition="Varchar",length=1024)
	@XmlElement(name="result")
	private String result;

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setDealDate(Date obj){
		this.dealDate = obj;
	}

	public Date getDealDate(){
		return dealDate;
	}

	public void setSts(Integer obj){
		this.sts = obj;
	}

	public Integer getSts(){
		return sts;
	}

	public void setSourceType(Integer obj){
		this.sourceType = obj;
	}

	public Integer getSourceType(){
		return sourceType;
	}

	public void setResult(String obj){
		this.result = obj;
	}

	public String getResult(){
		return result;
	}

	public CaRcData(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CaRcData rhs=(CaRcData)rhs0;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(createDate, rhs.createDate)) return false;
		if(!ObjectUtils.equals(dealDate, rhs.dealDate)) return false;
		if(!ObjectUtils.equals(sts, rhs.sts)) return false;
		if(!ObjectUtils.equals(sourceType, rhs.sourceType)) return false;
		if(!ObjectUtils.equals(result, rhs.result)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(acctId)
		.append(createDate)
		.append(dealDate)
		.append(sts)
		.append(sourceType)
		.append(result)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{acctId,createDate,dealDate,sts,sourceType,result}
}