package com.ailk.openbilling.persistence.itable.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="JD",name="I_ACCT_REL")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"groupId","relGroupId","relationshipType","titleRoleId","validDate","expireDate","operType","soNbr","commitDate"})
public class IAcctRel extends DataObject{


	@Column(name="GROUP_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="groupId")
	private Long groupId;

	@Column(name="REL_GROUP_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="relGroupId")
	private Long relGroupId;

	@Column(name="RELATIONSHIP_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="relationshipType")
	private Integer relationshipType;

	@Column(name="TITLE_ROLE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="titleRoleId")
	private Integer titleRoleId;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="OPER_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="operType")
	private Integer operType;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="COMMIT_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="commitDate")
	private Date commitDate;

	public void setGroupId(Long obj){
		this.groupId = obj;
	}

	public Long getGroupId(){
		return groupId;
	}

	public void setRelGroupId(Long obj){
		this.relGroupId = obj;
	}

	public Long getRelGroupId(){
		return relGroupId;
	}

	public void setRelationshipType(Integer obj){
		this.relationshipType = obj;
	}

	public Integer getRelationshipType(){
		return relationshipType;
	}

	public void setTitleRoleId(Integer obj){
		this.titleRoleId = obj;
	}

	public Integer getTitleRoleId(){
		return titleRoleId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setOperType(Integer obj){
		this.operType = obj;
	}

	public Integer getOperType(){
		return operType;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCommitDate(Date obj){
		this.commitDate = obj;
	}

	public Date getCommitDate(){
		return commitDate;
	}

	public IAcctRel(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		IAcctRel rhs=(IAcctRel)rhs0;
		if(!ObjectUtils.equals(groupId, rhs.groupId)) return false;
		if(!ObjectUtils.equals(relGroupId, rhs.relGroupId)) return false;
		if(!ObjectUtils.equals(relationshipType, rhs.relationshipType)) return false;
		if(!ObjectUtils.equals(titleRoleId, rhs.titleRoleId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(operType, rhs.operType)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(commitDate, rhs.commitDate)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(groupId)
		.append(relGroupId)
		.append(relationshipType)
		.append(titleRoleId)
		.append(validDate)
		.append(expireDate)
		.append(operType)
		.append(soNbr)
		.append(commitDate)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{groupId,relGroupId,relationshipType,titleRoleId,validDate,expireDate,operType,soNbr,commitDate}
}