package com.ailk.openbilling.persistence.itable.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="JD",name="I_ACCOUNT")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"custId","acctId","acctType","acctClass","acctSegment","acctName","status","measureId","dueDay","billDispatching","billLanguageId","provCode","countyCode","regionCode","creditSignControl","validDate","expireDate","operType","soNbr","commitDate","paymentType"})
public class IAccount extends DataObject{


	@Column(name="CUST_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="custId")
	private Long custId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="ACCT_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctType")
	private Integer acctType;

	@Column(name="ACCT_CLASS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctClass")
	private Integer acctClass;

	@Column(name="ACCT_SEGMENT",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctSegment")
	private Integer acctSegment;

	@Column(name="ACCT_NAME",columnDefinition="Varchar",length=256)
	@XmlElement(name="acctName")
	private String acctName;

	@Column(name="STATUS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="status")
	private Integer status;

	@Column(name="MEASURE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="measureId")
	private Integer measureId;

	@Column(name="DUE_DAY",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="dueDay")
	private Integer dueDay;

	@Column(name="BILL_DISPATCHING",columnDefinition="Varchar",length=32)
	@XmlElement(name="billDispatching")
	private String billDispatching;

	@Column(name="BILL_LANGUAGE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="billLanguageId")
	private Integer billLanguageId;

	@Column(name="PROV_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="provCode")
	private Integer provCode;

	@Column(name="COUNTY_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="countyCode")
	private Integer countyCode;

	@Column(name="REGION_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="regionCode")
	private Integer regionCode;

	@Column(name="CREDIT_SIGN_CONTROL",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="creditSignControl")
	private Integer creditSignControl;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="OPER_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="operType")
	private Integer operType;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="COMMIT_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="commitDate")
	private Date commitDate;

	@Column(name="PAYMENT_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="paymentType")
	private Integer paymentType;

	public void setCustId(Long obj){
		this.custId = obj;
	}

	public Long getCustId(){
		return custId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setAcctType(Integer obj){
		this.acctType = obj;
	}

	public Integer getAcctType(){
		return acctType;
	}

	public void setAcctClass(Integer obj){
		this.acctClass = obj;
	}

	public Integer getAcctClass(){
		return acctClass;
	}

	public void setAcctSegment(Integer obj){
		this.acctSegment = obj;
	}

	public Integer getAcctSegment(){
		return acctSegment;
	}

	public void setAcctName(String obj){
		this.acctName = obj;
	}

	public String getAcctName(){
		return acctName;
	}

	public void setStatus(Integer obj){
		this.status = obj;
	}

	public Integer getStatus(){
		return status;
	}

	public void setMeasureId(Integer obj){
		this.measureId = obj;
	}

	public Integer getMeasureId(){
		return measureId;
	}

	public void setDueDay(Integer obj){
		this.dueDay = obj;
	}

	public Integer getDueDay(){
		return dueDay;
	}

	public void setBillDispatching(String obj){
		this.billDispatching = obj;
	}

	public String getBillDispatching(){
		return billDispatching;
	}

	public void setBillLanguageId(Integer obj){
		this.billLanguageId = obj;
	}

	public Integer getBillLanguageId(){
		return billLanguageId;
	}

	public void setProvCode(Integer obj){
		this.provCode = obj;
	}

	public Integer getProvCode(){
		return provCode;
	}

	public void setCountyCode(Integer obj){
		this.countyCode = obj;
	}

	public Integer getCountyCode(){
		return countyCode;
	}

	public void setRegionCode(Integer obj){
		this.regionCode = obj;
	}

	public Integer getRegionCode(){
		return regionCode;
	}

	public void setCreditSignControl(Integer obj){
		this.creditSignControl = obj;
	}

	public Integer getCreditSignControl(){
		return creditSignControl;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setOperType(Integer obj){
		this.operType = obj;
	}

	public Integer getOperType(){
		return operType;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCommitDate(Date obj){
		this.commitDate = obj;
	}

	public Date getCommitDate(){
		return commitDate;
	}

	public void setPaymentType(Integer obj){
		this.paymentType = obj;
	}

	public Integer getPaymentType(){
		return paymentType;
	}

	public IAccount(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		IAccount rhs=(IAccount)rhs0;
		if(!ObjectUtils.equals(custId, rhs.custId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(acctType, rhs.acctType)) return false;
		if(!ObjectUtils.equals(acctClass, rhs.acctClass)) return false;
		if(!ObjectUtils.equals(acctSegment, rhs.acctSegment)) return false;
		if(!ObjectUtils.equals(acctName, rhs.acctName)) return false;
		if(!ObjectUtils.equals(status, rhs.status)) return false;
		if(!ObjectUtils.equals(measureId, rhs.measureId)) return false;
		if(!ObjectUtils.equals(dueDay, rhs.dueDay)) return false;
		if(!ObjectUtils.equals(billDispatching, rhs.billDispatching)) return false;
		if(!ObjectUtils.equals(billLanguageId, rhs.billLanguageId)) return false;
		if(!ObjectUtils.equals(provCode, rhs.provCode)) return false;
		if(!ObjectUtils.equals(countyCode, rhs.countyCode)) return false;
		if(!ObjectUtils.equals(regionCode, rhs.regionCode)) return false;
		if(!ObjectUtils.equals(creditSignControl, rhs.creditSignControl)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(operType, rhs.operType)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(commitDate, rhs.commitDate)) return false;
		if(!ObjectUtils.equals(paymentType, rhs.paymentType)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(custId)
		.append(acctId)
		.append(acctType)
		.append(acctClass)
		.append(acctSegment)
		.append(acctName)
		.append(status)
		.append(measureId)
		.append(dueDay)
		.append(billDispatching)
		.append(billLanguageId)
		.append(provCode)
		.append(countyCode)
		.append(regionCode)
		.append(creditSignControl)
		.append(validDate)
		.append(expireDate)
		.append(operType)
		.append(soNbr)
		.append(commitDate)
		.append(paymentType)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{custId,acctId,acctType,acctClass,acctSegment,acctName,status,measureId,dueDay,billDispatching,billLanguageId,provCode,countyCode,regionCode,creditSignControl,validDate,expireDate,operType,soNbr,commitDate,paymentType}
}