package com.ailk.openbilling.persistence.itable.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="JD",name="I_FEE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"userId","acctId","productId","feeType","feeItemId","srcFeeItemId","amount","measureId","busiSpecId","validDate","expireDate","operType","soNbr","commitDate"})
public class IFee extends DataObject{


	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="PRODUCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="productId")
	private Long productId;

	@Column(name="FEE_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="feeType")
	private Integer feeType;

	@Column(name="FEE_ITEM_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="feeItemId")
	private Integer feeItemId;

	@Column(name="SRC_FEE_ITEM_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="srcFeeItemId")
	private Integer srcFeeItemId;

	@Column(name="AMOUNT",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="amount")
	private Long amount;

	@Column(name="MEASURE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="measureId")
	private Integer measureId;

	@Column(name="BUSI_SPEC_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="busiSpecId")
	private Long busiSpecId;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="OPER_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="operType")
	private Integer operType;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="COMMIT_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="commitDate")
	private Date commitDate;

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setProductId(Long obj){
		this.productId = obj;
	}

	public Long getProductId(){
		return productId;
	}

	public void setFeeType(Integer obj){
		this.feeType = obj;
	}

	public Integer getFeeType(){
		return feeType;
	}

	public void setFeeItemId(Integer obj){
		this.feeItemId = obj;
	}

	public Integer getFeeItemId(){
		return feeItemId;
	}

	public void setSrcFeeItemId(Integer obj){
		this.srcFeeItemId = obj;
	}

	public Integer getSrcFeeItemId(){
		return srcFeeItemId;
	}

	public void setAmount(Long obj){
		this.amount = obj;
	}

	public Long getAmount(){
		return amount;
	}

	public void setMeasureId(Integer obj){
		this.measureId = obj;
	}

	public Integer getMeasureId(){
		return measureId;
	}

	public void setBusiSpecId(Long obj){
		this.busiSpecId = obj;
	}

	public Long getBusiSpecId(){
		return busiSpecId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setOperType(Integer obj){
		this.operType = obj;
	}

	public Integer getOperType(){
		return operType;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCommitDate(Date obj){
		this.commitDate = obj;
	}

	public Date getCommitDate(){
		return commitDate;
	}

	public IFee(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		IFee rhs=(IFee)rhs0;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(productId, rhs.productId)) return false;
		if(!ObjectUtils.equals(feeType, rhs.feeType)) return false;
		if(!ObjectUtils.equals(feeItemId, rhs.feeItemId)) return false;
		if(!ObjectUtils.equals(srcFeeItemId, rhs.srcFeeItemId)) return false;
		if(!ObjectUtils.equals(amount, rhs.amount)) return false;
		if(!ObjectUtils.equals(measureId, rhs.measureId)) return false;
		if(!ObjectUtils.equals(busiSpecId, rhs.busiSpecId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(operType, rhs.operType)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(commitDate, rhs.commitDate)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(userId)
		.append(acctId)
		.append(productId)
		.append(feeType)
		.append(feeItemId)
		.append(srcFeeItemId)
		.append(amount)
		.append(measureId)
		.append(busiSpecId)
		.append(validDate)
		.append(expireDate)
		.append(operType)
		.append(soNbr)
		.append(commitDate)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{userId,acctId,productId,feeType,feeItemId,srcFeeItemId,amount,measureId,busiSpecId,validDate,expireDate,operType,soNbr,commitDate}
}