package com.ailk.openbilling.persistence.itable.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="JD",name="I_PRODUCT")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"productId","userId","acctId","offerId","productType","productStatus","parentProductId","validDate","expireDate","operType","soNbr","commitDate"})
public class IProduct extends DataObject{


	@Column(name="PRODUCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="productId")
	private Long productId;

	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="OFFER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="offerId")
	private Long offerId;

	@Column(name="PRODUCT_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="productType")
	private Integer productType;

	@Column(name="PRODUCT_STATUS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="productStatus")
	private Integer productStatus;

	@Column(name="PARENT_PRODUCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="parentProductId")
	private Long parentProductId;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="OPER_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="operType")
	private Integer operType;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="COMMIT_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="commitDate")
	private Date commitDate;

	public void setProductId(Long obj){
		this.productId = obj;
	}

	public Long getProductId(){
		return productId;
	}

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setOfferId(Long obj){
		this.offerId = obj;
	}

	public Long getOfferId(){
		return offerId;
	}

	public void setProductType(Integer obj){
		this.productType = obj;
	}

	public Integer getProductType(){
		return productType;
	}

	public void setProductStatus(Integer obj){
		this.productStatus = obj;
	}

	public Integer getProductStatus(){
		return productStatus;
	}

	public void setParentProductId(Long obj){
		this.parentProductId = obj;
	}

	public Long getParentProductId(){
		return parentProductId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setOperType(Integer obj){
		this.operType = obj;
	}

	public Integer getOperType(){
		return operType;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCommitDate(Date obj){
		this.commitDate = obj;
	}

	public Date getCommitDate(){
		return commitDate;
	}

	public IProduct(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		IProduct rhs=(IProduct)rhs0;
		if(!ObjectUtils.equals(productId, rhs.productId)) return false;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(offerId, rhs.offerId)) return false;
		if(!ObjectUtils.equals(productType, rhs.productType)) return false;
		if(!ObjectUtils.equals(productStatus, rhs.productStatus)) return false;
		if(!ObjectUtils.equals(parentProductId, rhs.parentProductId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(operType, rhs.operType)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(commitDate, rhs.commitDate)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(productId)
		.append(userId)
		.append(acctId)
		.append(offerId)
		.append(productType)
		.append(productStatus)
		.append(parentProductId)
		.append(validDate)
		.append(expireDate)
		.append(operType)
		.append(soNbr)
		.append(commitDate)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{productId,userId,acctId,offerId,productType,productStatus,parentProductId,validDate,expireDate,operType,soNbr,commitDate}
}