package com.ailk.openbilling.persistence.itable.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="JD",name="I_USER_ACCT_REL")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"userId","acctId","oldAcctId","relationshipType","titleRoleId","validDate","expireDate","operType","soNbr","commitDate"})
public class IUserAcctRel extends DataObject{


	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="OLD_ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="oldAcctId")
	private Long oldAcctId;

	/**
	 * 0:??,??
	 */
	@Column(name="RELATIONSHIP_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="relationshipType")
	private Integer relationshipType;

	/**
	 * ??????
??????:
1000:????(??)
1001:???
1002:???
1003:??
??????:
3000:????(??)
3001:???
3002:??
3003:??
3004:??
3005:??
3006: ????
??????
8000:????(single Balance??????)
8001:????(??:?????)
VPN/community??????
41:MAINPHONE
42:NORMAL
	 */
	@Column(name="TITLE_ROLE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="titleRoleId")
	private Integer titleRoleId;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="expireDate")
	private Date expireDate;

	/**
	 * 1:??
2:??
3:??
	 */
	@Column(name="OPER_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="operType")
	private Integer operType;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="COMMIT_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="commitDate")
	private Date commitDate;

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setOldAcctId(Long obj){
		this.oldAcctId = obj;
	}

	public Long getOldAcctId(){
		return oldAcctId;
	}

	public void setRelationshipType(Integer obj){
		this.relationshipType = obj;
	}

	public Integer getRelationshipType(){
		return relationshipType;
	}

	public void setTitleRoleId(Integer obj){
		this.titleRoleId = obj;
	}

	public Integer getTitleRoleId(){
		return titleRoleId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setOperType(Integer obj){
		this.operType = obj;
	}

	public Integer getOperType(){
		return operType;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCommitDate(Date obj){
		this.commitDate = obj;
	}

	public Date getCommitDate(){
		return commitDate;
	}

	public IUserAcctRel(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		IUserAcctRel rhs=(IUserAcctRel)rhs0;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(oldAcctId, rhs.oldAcctId)) return false;
		if(!ObjectUtils.equals(relationshipType, rhs.relationshipType)) return false;
		if(!ObjectUtils.equals(titleRoleId, rhs.titleRoleId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(operType, rhs.operType)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(commitDate, rhs.commitDate)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(userId)
		.append(acctId)
		.append(oldAcctId)
		.append(relationshipType)
		.append(titleRoleId)
		.append(validDate)
		.append(expireDate)
		.append(operType)
		.append(soNbr)
		.append(commitDate)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{userId,acctId,oldAcctId,relationshipType,titleRoleId,validDate,expireDate,operType,soNbr,commitDate}
}