package com.ailk.openbilling.persistence.itable.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="JD",name="I_USER_SHARE_REL")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"shareId","userId","viceUserId","roleType","regionCode","validDate","expireDate","soNbr","operType","commitDate","remark"})
public class IUserShareRel extends DataObject{


	@Column(name="SHARE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="shareId")
	private Long shareId;

	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="VICE_USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="viceUserId")
	private Long viceUserId;

	@Column(name="ROLE_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="roleType")
	private Integer roleType;

	@Column(name="REGION_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="regionCode")
	private Integer regionCode;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="OPER_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="operType")
	private Integer operType;

	@Column(name="COMMIT_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="commitDate")
	private Date commitDate;

	@Column(name="REMARK",columnDefinition="Varchar",length=255)
	@XmlElement(name="remark")
	private String remark;

	public void setShareId(Long obj){
		this.shareId = obj;
	}

	public Long getShareId(){
		return shareId;
	}

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setViceUserId(Long obj){
		this.viceUserId = obj;
	}

	public Long getViceUserId(){
		return viceUserId;
	}

	public void setRoleType(Integer obj){
		this.roleType = obj;
	}

	public Integer getRoleType(){
		return roleType;
	}

	public void setRegionCode(Integer obj){
		this.regionCode = obj;
	}

	public Integer getRegionCode(){
		return regionCode;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setOperType(Integer obj){
		this.operType = obj;
	}

	public Integer getOperType(){
		return operType;
	}

	public void setCommitDate(Date obj){
		this.commitDate = obj;
	}

	public Date getCommitDate(){
		return commitDate;
	}

	public void setRemark(String obj){
		this.remark = obj;
	}

	public String getRemark(){
		return remark;
	}

	public IUserShareRel(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		IUserShareRel rhs=(IUserShareRel)rhs0;
		if(!ObjectUtils.equals(shareId, rhs.shareId)) return false;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(viceUserId, rhs.viceUserId)) return false;
		if(!ObjectUtils.equals(roleType, rhs.roleType)) return false;
		if(!ObjectUtils.equals(regionCode, rhs.regionCode)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(operType, rhs.operType)) return false;
		if(!ObjectUtils.equals(commitDate, rhs.commitDate)) return false;
		if(!ObjectUtils.equals(remark, rhs.remark)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(shareId)
		.append(userId)
		.append(viceUserId)
		.append(roleType)
		.append(regionCode)
		.append(validDate)
		.append(expireDate)
		.append(soNbr)
		.append(operType)
		.append(commitDate)
		.append(remark)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{shareId,userId,viceUserId,roleType,regionCode,validDate,expireDate,soNbr,operType,commitDate,remark}
}