package com.ailk.openbilling.persistence.itable.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="JD",name="I_USER_SUB_SERVICE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"userId","acctId","serviceId","balance","type","regionCode","busiCode","creditLevel","monitorPlan","validDate","expireDate","operType","soNbr","commitDate"})
public class IUserSubService extends DataObject{


	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="SERVICE_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="serviceId")
	private Integer serviceId;

	@Column(name="BALANCE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="balance")
	private Integer balance;

	@Column(name="TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="type")
	private Short type;

	@Column(name="REGION_CODE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="regionCode")
	private Integer regionCode;

	@Column(name="BUSI_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="busiCode")
	private Integer busiCode;

	@Column(name="CREDIT_LEVEL",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="creditLevel")
	private Integer creditLevel;

	@Column(name="MONITOR_PLAN",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="monitorPlan")
	private Integer monitorPlan;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="OPER_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="operType")
	private Integer operType;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="COMMIT_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="commitDate")
	private Date commitDate;

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setServiceId(Integer obj){
		this.serviceId = obj;
	}

	public Integer getServiceId(){
		return serviceId;
	}

	public void setBalance(Integer obj){
		this.balance = obj;
	}

	public Integer getBalance(){
		return balance;
	}

	public void setType(Short obj){
		this.type = obj;
	}

	public Short getType(){
		return type;
	}

	public void setRegionCode(Integer obj){
		this.regionCode = obj;
	}

	public Integer getRegionCode(){
		return regionCode;
	}

	public void setBusiCode(Integer obj){
		this.busiCode = obj;
	}

	public Integer getBusiCode(){
		return busiCode;
	}

	public void setCreditLevel(Integer obj){
		this.creditLevel = obj;
	}

	public Integer getCreditLevel(){
		return creditLevel;
	}

	public void setMonitorPlan(Integer obj){
		this.monitorPlan = obj;
	}

	public Integer getMonitorPlan(){
		return monitorPlan;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setOperType(Integer obj){
		this.operType = obj;
	}

	public Integer getOperType(){
		return operType;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCommitDate(Date obj){
		this.commitDate = obj;
	}

	public Date getCommitDate(){
		return commitDate;
	}

	public IUserSubService(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		IUserSubService rhs=(IUserSubService)rhs0;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(serviceId, rhs.serviceId)) return false;
		if(!ObjectUtils.equals(balance, rhs.balance)) return false;
		if(!ObjectUtils.equals(type, rhs.type)) return false;
		if(!ObjectUtils.equals(regionCode, rhs.regionCode)) return false;
		if(!ObjectUtils.equals(busiCode, rhs.busiCode)) return false;
		if(!ObjectUtils.equals(creditLevel, rhs.creditLevel)) return false;
		if(!ObjectUtils.equals(monitorPlan, rhs.monitorPlan)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(operType, rhs.operType)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(commitDate, rhs.commitDate)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(userId)
		.append(acctId)
		.append(serviceId)
		.append(balance)
		.append(type)
		.append(regionCode)
		.append(busiCode)
		.append(creditLevel)
		.append(monitorPlan)
		.append(validDate)
		.append(expireDate)
		.append(operType)
		.append(soNbr)
		.append(commitDate)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{userId,acctId,serviceId,balance,type,regionCode,busiCode,creditLevel,monitorPlan,validDate,expireDate,operType,soNbr,commitDate}
}