package com.ailk.openbilling.persistence.itable.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="JD",name="I_USER_SERV_STATUS")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"serviceInstId","userId","serviceId","osSts","osStsDtl","validDate","expireDate","operType","soNbr","commitDate","remark"})
public class IUserServStatus extends DataObject{


	@Column(name="SERVICE_INST_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="serviceInstId")
	private Long serviceInstId;

	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="SERVICE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="serviceId")
	private Integer serviceId;

	@Column(name="OS_STS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="osSts")
	private Integer osSts;

	@Column(name="OS_STS_DTL",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="osStsDtl")
	private Long osStsDtl;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="OPER_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="operType")
	private Integer operType;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="COMMIT_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="commitDate")
	private Date commitDate;

	@Column(name="REMARK",columnDefinition="Varchar",length=255)
	@XmlElement(name="remark")
	private String remark;

	public void setServiceInstId(Long obj){
		this.serviceInstId = obj;
	}

	public Long getServiceInstId(){
		return serviceInstId;
	}

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setServiceId(Integer obj){
		this.serviceId = obj;
	}

	public Integer getServiceId(){
		return serviceId;
	}

	public void setOsSts(Integer obj){
		this.osSts = obj;
	}

	public Integer getOsSts(){
		return osSts;
	}

	public void setOsStsDtl(Long obj){
		this.osStsDtl = obj;
	}

	public Long getOsStsDtl(){
		return osStsDtl;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setOperType(Integer obj){
		this.operType = obj;
	}

	public Integer getOperType(){
		return operType;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCommitDate(Date obj){
		this.commitDate = obj;
	}

	public Date getCommitDate(){
		return commitDate;
	}

	public void setRemark(String obj){
		this.remark = obj;
	}

	public String getRemark(){
		return remark;
	}

	public IUserServStatus(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		IUserServStatus rhs=(IUserServStatus)rhs0;
		if(!ObjectUtils.equals(serviceInstId, rhs.serviceInstId)) return false;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(serviceId, rhs.serviceId)) return false;
		if(!ObjectUtils.equals(osSts, rhs.osSts)) return false;
		if(!ObjectUtils.equals(osStsDtl, rhs.osStsDtl)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(operType, rhs.operType)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(commitDate, rhs.commitDate)) return false;
		if(!ObjectUtils.equals(remark, rhs.remark)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(serviceInstId)
		.append(userId)
		.append(serviceId)
		.append(osSts)
		.append(osStsDtl)
		.append(validDate)
		.append(expireDate)
		.append(operType)
		.append(soNbr)
		.append(commitDate)
		.append(remark)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{serviceInstId,userId,serviceId,osSts,osStsDtl,validDate,expireDate,operType,soNbr,commitDate,remark}
}