package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="CD",name="CM_CUST_VIP")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"resourceId","custId","usecustId","vipState","vipClass","vipType","custManagerId","createDate","validDate","expireDate","soNbr","soDate","remark"})
public class CmCustVip extends DataObject{


	@Id
	@Column(name="RESOURCE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="resourceId")
	private Long resourceId;

	@Column(name="CUST_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="custId")
	private Long custId;

	@Id
	@Column(name="USECUST_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="usecustId")
	private Long usecustId;

	@Column(name="VIP_STATE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="vipState")
	private Integer vipState;

	@Column(name="VIP_CLASS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="vipClass")
	private Integer vipClass;

	@Column(name="VIP_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="vipType")
	private Integer vipType;

	@Column(name="CUST_MANAGER_ID",columnDefinition="Char",length=8)
	@XmlElement(name="custManagerId")
	private String custManagerId;

	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	@Id
	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Id
	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="SO_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="soDate")
	private Date soDate;

	@Column(name="REMARK",columnDefinition="Varchar",length=255)
	@XmlElement(name="remark")
	private String remark;

	public void setResourceId(Long obj){
		this.resourceId = obj;
	}

	public Long getResourceId(){
		return resourceId;
	}

	public void setCustId(Long obj){
		this.custId = obj;
	}

	public Long getCustId(){
		return custId;
	}

	public void setUsecustId(Long obj){
		this.usecustId = obj;
	}

	public Long getUsecustId(){
		return usecustId;
	}

	public void setVipState(Integer obj){
		this.vipState = obj;
	}

	public Integer getVipState(){
		return vipState;
	}

	public void setVipClass(Integer obj){
		this.vipClass = obj;
	}

	public Integer getVipClass(){
		return vipClass;
	}

	public void setVipType(Integer obj){
		this.vipType = obj;
	}

	public Integer getVipType(){
		return vipType;
	}

	public void setCustManagerId(String obj){
		this.custManagerId = obj;
	}

	public String getCustManagerId(){
		return custManagerId;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setSoDate(Date obj){
		this.soDate = obj;
	}

	public Date getSoDate(){
		return soDate;
	}

	public void setRemark(String obj){
		this.remark = obj;
	}

	public String getRemark(){
		return remark;
	}

	public CmCustVip(){
	}

	public CmCustVip(Long resourceId,Long usecustId,Date validDate,Long soNbr){
		this.resourceId = resourceId;
		this.usecustId = usecustId;
		this.validDate = validDate;
		this.soNbr = soNbr;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CmCustVip rhs=(CmCustVip)rhs0;
		if(!ObjectUtils.equals(resourceId, rhs.resourceId)) return false;
		if(!ObjectUtils.equals(usecustId, rhs.usecustId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(resourceId)
		.append(usecustId)
		.append(validDate)
		.append(soNbr)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{resourceId,custId,usecustId,vipState,vipClass,vipType,custManagerId,createDate,validDate,expireDate,soNbr,soDate,remark}
}