package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="CD",name="CM_FIRST_ACTIVE_TASK_HIS")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"userId","phoneId","activationTime","acctId","smsLanguage","ivrLanguage","ussdLanguage","productId","destOfferingId","referOfferingId","pricingPlanId","rewardId","dealSts","createDate","dealDate","dealDesc","dealAgainDate","soNbr"})
public class CmFirstActiveTaskHis extends DataObject{


	/**
	 * 用户编号
	 */
	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	/**
	 * 手机号码
	 */
	@Column(name="PHONE_ID",columnDefinition="Varchar",length=64)
	@XmlElement(name="phoneId")
	private String phoneId;

	/**
	 * 首次激活时间
	 */
	@Column(name="ACTIVATION_TIME",columnDefinition="TimeStamp")
	@XmlElement(name="activationTime")
	private Date activationTime;

	/**
	 * 账户编号
	 */
	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	/**
	 * The language ID which will be used when read information alternately
from sys_language
---READING_LANGUAGE
	 */
	@Column(name="SMS_LANGUAGE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="smsLanguage")
	private Integer smsLanguage;

	/**
	 * The language ID which will be used when listen information alternately
from sys_language
---LISTENING_LANGUAGE
	 */
	@Column(name="IVR_LANGUAGE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="ivrLanguage")
	private Integer ivrLanguage;

	/**
	 * The language ID which will be used when write information alternately
from sys_language
--WRITING_LANGUAGE
	 */
	@Column(name="USSD_LANGUAGE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="ussdLanguage")
	private Integer ussdLanguage;

	@Column(name="PRODUCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="productId")
	private Long productId;

	/**
	 * 转换到的目标销售品标识
	 */
	@Column(name="DEST_OFFERING_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="destOfferingId")
	private Integer destOfferingId;

	/**
	 * 原销售品标识
	 */
	@Column(name="REFER_OFFERING_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="referOfferingId")
	private Integer referOfferingId;

	@Column(name="PRICING_PLAN_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="pricingPlanId")
	private Integer pricingPlanId;

	/**
	 * reward id
	 */
	@Column(name="REWARD_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="rewardId")
	private Integer rewardId;

	/**
	 * 1：成功 2：失败 3：处理中 4:待处理
	 */
	@Column(name="DEAL_STS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="dealSts")
	private Integer dealSts;

	/**
	 * 记录生成时间
	 */
	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	/**
	 * 处理时间
	 */
	@Column(name="DEAL_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealDate")
	private Date dealDate;

	/**
	 * 失败时，存储失败信息
	 */
	@Column(name="DEAL_DESC",columnDefinition="Varchar",length=255)
	@XmlElement(name="dealDesc")
	private String dealDesc;

	/**
	 * 对于失败记录的再处理时间
	 */
	@Column(name="DEAL_AGAIN_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealAgainDate")
	private Date dealAgainDate;

	/**
	 * 记录工单号
	 */
	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setPhoneId(String obj){
		this.phoneId = obj;
	}

	public String getPhoneId(){
		return phoneId;
	}

	public void setActivationTime(Date obj){
		this.activationTime = obj;
	}

	public Date getActivationTime(){
		return activationTime;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setSmsLanguage(Integer obj){
		this.smsLanguage = obj;
	}

	public Integer getSmsLanguage(){
		return smsLanguage;
	}

	public void setIvrLanguage(Integer obj){
		this.ivrLanguage = obj;
	}

	public Integer getIvrLanguage(){
		return ivrLanguage;
	}

	public void setUssdLanguage(Integer obj){
		this.ussdLanguage = obj;
	}

	public Integer getUssdLanguage(){
		return ussdLanguage;
	}

	public void setProductId(Long obj){
		this.productId = obj;
	}

	public Long getProductId(){
		return productId;
	}

	public void setDestOfferingId(Integer obj){
		this.destOfferingId = obj;
	}

	public Integer getDestOfferingId(){
		return destOfferingId;
	}

	public void setReferOfferingId(Integer obj){
		this.referOfferingId = obj;
	}

	public Integer getReferOfferingId(){
		return referOfferingId;
	}

	public void setPricingPlanId(Integer obj){
		this.pricingPlanId = obj;
	}

	public Integer getPricingPlanId(){
		return pricingPlanId;
	}

	public void setRewardId(Integer obj){
		this.rewardId = obj;
	}

	public Integer getRewardId(){
		return rewardId;
	}

	public void setDealSts(Integer obj){
		this.dealSts = obj;
	}

	public Integer getDealSts(){
		return dealSts;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setDealDate(Date obj){
		this.dealDate = obj;
	}

	public Date getDealDate(){
		return dealDate;
	}

	public void setDealDesc(String obj){
		this.dealDesc = obj;
	}

	public String getDealDesc(){
		return dealDesc;
	}

	public void setDealAgainDate(Date obj){
		this.dealAgainDate = obj;
	}

	public Date getDealAgainDate(){
		return dealAgainDate;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public CmFirstActiveTaskHis(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CmFirstActiveTaskHis rhs=(CmFirstActiveTaskHis)rhs0;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(phoneId, rhs.phoneId)) return false;
		if(!ObjectUtils.equals(activationTime, rhs.activationTime)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(smsLanguage, rhs.smsLanguage)) return false;
		if(!ObjectUtils.equals(ivrLanguage, rhs.ivrLanguage)) return false;
		if(!ObjectUtils.equals(ussdLanguage, rhs.ussdLanguage)) return false;
		if(!ObjectUtils.equals(productId, rhs.productId)) return false;
		if(!ObjectUtils.equals(destOfferingId, rhs.destOfferingId)) return false;
		if(!ObjectUtils.equals(referOfferingId, rhs.referOfferingId)) return false;
		if(!ObjectUtils.equals(pricingPlanId, rhs.pricingPlanId)) return false;
		if(!ObjectUtils.equals(rewardId, rhs.rewardId)) return false;
		if(!ObjectUtils.equals(dealSts, rhs.dealSts)) return false;
		if(!ObjectUtils.equals(createDate, rhs.createDate)) return false;
		if(!ObjectUtils.equals(dealDate, rhs.dealDate)) return false;
		if(!ObjectUtils.equals(dealDesc, rhs.dealDesc)) return false;
		if(!ObjectUtils.equals(dealAgainDate, rhs.dealAgainDate)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(userId)
		.append(phoneId)
		.append(activationTime)
		.append(acctId)
		.append(smsLanguage)
		.append(ivrLanguage)
		.append(ussdLanguage)
		.append(productId)
		.append(destOfferingId)
		.append(referOfferingId)
		.append(pricingPlanId)
		.append(rewardId)
		.append(dealSts)
		.append(createDate)
		.append(dealDate)
		.append(dealDesc)
		.append(dealAgainDate)
		.append(soNbr)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{userId,phoneId,activationTime,acctId,smsLanguage,ivrLanguage,ussdLanguage,productId,destOfferingId,referOfferingId,pricingPlanId,rewardId,dealSts,createDate,dealDate,dealDesc,dealAgainDate,soNbr}
}