package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="CD",name="CM_INDIVIDUAL")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"partyId","gender","maritalStatus","skills","birthDate","incomeLevel","industryId","religionId","educationLevel","occupationId","countryOfBirth","placeOfBirth","createDate","validDate","expireDate","soNbr","soDate"})
public class CmIndividual extends DataObject{


	/**
	 * Participation Persion's Unique Numbering
	 */
	@Id
	@Column(name="PARTY_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="partyId")
	private Long partyId;

	/**
	 * Sex
	 */
	@Column(name="GENDER",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="gender")
	private Integer gender;

	/**
	 * Marital Status        0：spinsterhood    1：Married
	 */
	@Column(name="MARITAL_STATUS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="maritalStatus")
	private Integer maritalStatus;

	/**
	 * Specialty  Information Describtion
	 */
	@Column(name="SKILLS",columnDefinition="Varchar",length=256)
	@XmlElement(name="skills")
	private String skills;

	/**
	 * Birthday
	 */
	@Column(name="BIRTH_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="birthDate")
	private Date birthDate;

	/**
	 * Income State        0：0~1000    1：1000~3000    2：3000~10000    3：10000~
	 */
	@Column(name="INCOME_LEVEL",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="incomeLevel")
	private Integer incomeLevel;

	/**
	 * Adscription Industrry,find it in the Industry Definition Table
	 */
	@Column(name="INDUSTRY_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="industryId")
	private Integer industryId;

	/**
	 * Religious Belief            1: Buddhism    2: Islam    3: Christ    4: Catholicism
	 */
	@Column(name="RELIGION_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="religionId")
	private Integer religionId;

	/**
	 * Education        0: Junior middle school and the bellow    1: High school    2: Undergraduate    3: Master    4: Doctor and the above
	 */
	@Column(name="EDUCATION_LEVEL",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="educationLevel")
	private Integer educationLevel;

	/**
	 * Job
	 */
	@Column(name="OCCUPATION_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="occupationId")
	private Integer occupationId;

	/**
	 * Country,get the code from  SYS_COUNTRY
	 */
	@Column(name="COUNTRY_OF_BIRTH",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="countryOfBirth")
	private Integer countryOfBirth;

	/**
	 * Birthplace
	 */
	@Column(name="PLACE_OF_BIRTH",columnDefinition="Varchar",length=64)
	@XmlElement(name="placeOfBirth")
	private String placeOfBirth;

	/**
	 * record create date
	 */
	@Column(name="CREATE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="createDate")
	private Date createDate;

	/**
	 * Effective Date
	 */
	@Id
	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	/**
	 * Expired Date
	 */
	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="expireDate")
	private Date expireDate;

	/**
	 * The serial number
	 */
	@Id
	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="SO_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="soDate")
	private Date soDate;

	public void setPartyId(Long obj){
		this.partyId = obj;
	}

	public Long getPartyId(){
		return partyId;
	}

	public void setGender(Integer obj){
		this.gender = obj;
	}

	public Integer getGender(){
		return gender;
	}

	public void setMaritalStatus(Integer obj){
		this.maritalStatus = obj;
	}

	public Integer getMaritalStatus(){
		return maritalStatus;
	}

	public void setSkills(String obj){
		this.skills = obj;
	}

	public String getSkills(){
		return skills;
	}

	public void setBirthDate(Date obj){
		this.birthDate = obj;
	}

	public Date getBirthDate(){
		return birthDate;
	}

	public void setIncomeLevel(Integer obj){
		this.incomeLevel = obj;
	}

	public Integer getIncomeLevel(){
		return incomeLevel;
	}

	public void setIndustryId(Integer obj){
		this.industryId = obj;
	}

	public Integer getIndustryId(){
		return industryId;
	}

	public void setReligionId(Integer obj){
		this.religionId = obj;
	}

	public Integer getReligionId(){
		return religionId;
	}

	public void setEducationLevel(Integer obj){
		this.educationLevel = obj;
	}

	public Integer getEducationLevel(){
		return educationLevel;
	}

	public void setOccupationId(Integer obj){
		this.occupationId = obj;
	}

	public Integer getOccupationId(){
		return occupationId;
	}

	public void setCountryOfBirth(Integer obj){
		this.countryOfBirth = obj;
	}

	public Integer getCountryOfBirth(){
		return countryOfBirth;
	}

	public void setPlaceOfBirth(String obj){
		this.placeOfBirth = obj;
	}

	public String getPlaceOfBirth(){
		return placeOfBirth;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setSoDate(Date obj){
		this.soDate = obj;
	}

	public Date getSoDate(){
		return soDate;
	}

	public CmIndividual(){
	}

	public CmIndividual(Long partyId,Date validDate,Long soNbr){
		this.partyId = partyId;
		this.validDate = validDate;
		this.soNbr = soNbr;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CmIndividual rhs=(CmIndividual)rhs0;
		if(!ObjectUtils.equals(partyId, rhs.partyId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(partyId)
		.append(validDate)
		.append(soNbr)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{partyId,gender,maritalStatus,skills,birthDate,incomeLevel,industryId,religionId,educationLevel,occupationId,countryOfBirth,placeOfBirth,createDate,validDate,expireDate,soNbr,soDate}
}