package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="cd",name="CM_MKT_ACT")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"offerId","resourceId","offerName","offerTag","offerType","validDate","expireDate","soNbr","createDate","soDate"})
public class CmMktAct extends DataObject{


	/**
	 * 活动编号
	 */
	@Id
	@Column(name="OFFER_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="offerId")
	private Long offerId;

	/**
	 * 用户编号
	 */
	@Id
	@Column(name="RESOURCE_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resourceId")
	private Long resourceId;

	/**
	 * 活动名称
	 */
	@Column(name="OFFER_NAME",columnDefinition="Varchar",length=200)
	@XmlElement(name="offerName")
	private String offerName;

	/**
	 * 活动标签
	 */
	@Column(name="OFFER_TAG",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="offerTag")
	private Integer offerTag;

	/**
	 * 捆绑类型
	 */
	@Column(name="OFFER_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="offerType")
	private Integer offerType;

	/**
	 * 生效时间
	 */
	@Id
	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	/**
	 * 失效时间
	 */
	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	/**
	 * 工单号
	 */
	@Id
	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="soNbr")
	private Long soNbr;

	/**
	 * 创建时间
	 */
	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	/**
	 * 时间流水
	 */
	@Column(name="SO_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="soDate")
	private Date soDate;

	public void setOfferId(Long obj){
		this.offerId = obj;
	}

	public Long getOfferId(){
		return offerId;
	}

	public void setResourceId(Long obj){
		this.resourceId = obj;
	}

	public Long getResourceId(){
		return resourceId;
	}

	public void setOfferName(String obj){
		this.offerName = obj;
	}

	public String getOfferName(){
		return offerName;
	}

	public void setOfferTag(Integer obj){
		this.offerTag = obj;
	}

	public Integer getOfferTag(){
		return offerTag;
	}

	public void setOfferType(Integer obj){
		this.offerType = obj;
	}

	public Integer getOfferType(){
		return offerType;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setSoDate(Date obj){
		this.soDate = obj;
	}

	public Date getSoDate(){
		return soDate;
	}

	public CmMktAct(){
	}

	public CmMktAct(Long offerId,Long resourceId,Date validDate,Long soNbr){
		this.offerId = offerId;
		this.resourceId = resourceId;
		this.validDate = validDate;
		this.soNbr = soNbr;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CmMktAct rhs=(CmMktAct)rhs0;
		if(!ObjectUtils.equals(resourceId, rhs.resourceId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(offerId, rhs.offerId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(resourceId)
		.append(validDate)
		.append(soNbr)
		.append(offerId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{offerId,resourceId,offerName,offerTag,offerType,validDate,expireDate,soNbr,createDate,soDate}
}