package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="CD",name="CM_ONETIME_FEE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"custId","acctId","userId","phoneId","payAcctId","origSoNbr","orderType","feeItemCode","chargeType","amount","billType","remark","soOnetimeId","feeItemSeq","soNbr","feeItemDate"})
public class CmOnetimeFee extends DataObject{


	@Column(name="CUST_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="custId")
	private Long custId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="PHONE_ID",columnDefinition="Varchar",length=64)
	@XmlElement(name="phoneId")
	private String phoneId;

	@Column(name="PAY_ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="payAcctId")
	private Long payAcctId;

	/**
	 * The order number of order for which the onetime fee is charged
	 */
	@Column(name="ORIG_SO_NBR",columnDefinition="Varchar",length=128)
	@XmlElement(name="origSoNbr")
	private String origSoNbr;

	@Column(name="ORDER_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="orderType")
	private Integer orderType;

	@Column(name="FEE_ITEM_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="feeItemCode")
	private Integer feeItemCode;

	@Column(name="CHARGE_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="chargeType")
	private Integer chargeType;

	@Column(name="AMOUNT",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="amount")
	private Long amount;

	@Column(name="BILL_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="billType")
	private Integer billType;

	@Column(name="REMARK",columnDefinition="Varchar",length=256)
	@XmlElement(name="remark")
	private String remark;

	@Column(name="SO_ONETIME_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soOnetimeId")
	private Long soOnetimeId;

	/**
	 * sequence of feeitem ，which returned by account
	 */
	@Column(name="FEE_ITEM_SEQ",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="feeItemSeq")
	private Long feeItemSeq;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="FEE_ITEM_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="feeItemDate")
	private Date feeItemDate;

	public void setCustId(Long obj){
		this.custId = obj;
	}

	public Long getCustId(){
		return custId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setPhoneId(String obj){
		this.phoneId = obj;
	}

	public String getPhoneId(){
		return phoneId;
	}

	public void setPayAcctId(Long obj){
		this.payAcctId = obj;
	}

	public Long getPayAcctId(){
		return payAcctId;
	}

	public void setOrigSoNbr(String obj){
		this.origSoNbr = obj;
	}

	public String getOrigSoNbr(){
		return origSoNbr;
	}

	public void setOrderType(Integer obj){
		this.orderType = obj;
	}

	public Integer getOrderType(){
		return orderType;
	}

	public void setFeeItemCode(Integer obj){
		this.feeItemCode = obj;
	}

	public Integer getFeeItemCode(){
		return feeItemCode;
	}

	public void setChargeType(Integer obj){
		this.chargeType = obj;
	}

	public Integer getChargeType(){
		return chargeType;
	}

	public void setAmount(Long obj){
		this.amount = obj;
	}

	public Long getAmount(){
		return amount;
	}

	public void setBillType(Integer obj){
		this.billType = obj;
	}

	public Integer getBillType(){
		return billType;
	}

	public void setRemark(String obj){
		this.remark = obj;
	}

	public String getRemark(){
		return remark;
	}

	public void setSoOnetimeId(Long obj){
		this.soOnetimeId = obj;
	}

	public Long getSoOnetimeId(){
		return soOnetimeId;
	}

	public void setFeeItemSeq(Long obj){
		this.feeItemSeq = obj;
	}

	public Long getFeeItemSeq(){
		return feeItemSeq;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setFeeItemDate(Date obj){
		this.feeItemDate = obj;
	}

	public Date getFeeItemDate(){
		return feeItemDate;
	}

	public CmOnetimeFee(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CmOnetimeFee rhs=(CmOnetimeFee)rhs0;
		if(!ObjectUtils.equals(custId, rhs.custId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(phoneId, rhs.phoneId)) return false;
		if(!ObjectUtils.equals(payAcctId, rhs.payAcctId)) return false;
		if(!ObjectUtils.equals(origSoNbr, rhs.origSoNbr)) return false;
		if(!ObjectUtils.equals(orderType, rhs.orderType)) return false;
		if(!ObjectUtils.equals(feeItemCode, rhs.feeItemCode)) return false;
		if(!ObjectUtils.equals(chargeType, rhs.chargeType)) return false;
		if(!ObjectUtils.equals(amount, rhs.amount)) return false;
		if(!ObjectUtils.equals(billType, rhs.billType)) return false;
		if(!ObjectUtils.equals(remark, rhs.remark)) return false;
		if(!ObjectUtils.equals(soOnetimeId, rhs.soOnetimeId)) return false;
		if(!ObjectUtils.equals(feeItemSeq, rhs.feeItemSeq)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(feeItemDate, rhs.feeItemDate)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(custId)
		.append(acctId)
		.append(userId)
		.append(phoneId)
		.append(payAcctId)
		.append(origSoNbr)
		.append(orderType)
		.append(feeItemCode)
		.append(chargeType)
		.append(amount)
		.append(billType)
		.append(remark)
		.append(soOnetimeId)
		.append(feeItemSeq)
		.append(soNbr)
		.append(feeItemDate)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{custId,acctId,userId,phoneId,payAcctId,origSoNbr,orderType,feeItemCode,chargeType,amount,billType,remark,soOnetimeId,feeItemSeq,soNbr,feeItemDate}
}