package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="CD",name="CM_RES_LAST_ICS")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"resourceId","phoneId","callScreenNoType","effectTime","expireTime","weekStart","weekStop","expireDate","routeNumber","irRouteFlag","routingMethod","listType","createDate","validDate","soNbr","soDate"})
public class CmResLastIcs extends DataObject{


	/**
	 * RESOURCE_ID
	 */
	@Column(name="RESOURCE_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resourceId")
	private Long resourceId;

	/**
	 * PHONE_ID
	 */
	@Column(name="PHONE_ID",columnDefinition="Varchar",length=64,nullable=false)
	@XmlElement(name="phoneId")
	private String phoneId;

	/**
	 * 1: blacklist
2: whitelist
3:blacklist & whitelist(default)
	 */
	@Column(name="CALL_SCREEN_NO_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="callScreenNoType")
	private Integer callScreenNoType;

	/**
	 * EFFECT_TIME
	 */
	@Column(name="EFFECT_TIME",columnDefinition="Varchar",length=64)
	@XmlElement(name="effectTime")
	private String effectTime;

	/**
	 * EXPIRE_TIME
	 */
	@Column(name="EXPIRE_TIME",columnDefinition="Varchar",length=64)
	@XmlElement(name="expireTime")
	private String expireTime;

	/**
	 * WEEK_START
	 */
	@Column(name="WEEK_START",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="weekStart")
	private Integer weekStart;

	/**
	 * WEEK_STOP
	 */
	@Column(name="WEEK_STOP",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="weekStop")
	private Integer weekStop;

	/**
	 * EXPIRE_DATE
	 */
	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	/**
	 * ROUTE_NUMBER
	 */
	@Column(name="ROUTE_NUMBER",columnDefinition="Varchar",length=64)
	@XmlElement(name="routeNumber")
	private String routeNumber;

	/**
	 * IR_ROUTE_FLAG
	 */
	@Column(name="IR_ROUTE_FLAG",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="irRouteFlag")
	private Integer irRouteFlag;

	/**
	 * ROUTING_METHOD
	 */
	@Column(name="ROUTING_METHOD",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="routingMethod")
	private Integer routingMethod;

	/**
	 * 0: Black List
1: White List
	 */
	@Column(name="LIST_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="listType")
	private Integer listType;

	/**
	 * CREATE_DATE
	 */
	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	/**
	 * VALID_DATE
	 */
	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	/**
	 * SO_NBR
	 */
	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	/**
	 * SO_DATE
	 */
	@Column(name="SO_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="soDate")
	private Date soDate;

	public void setResourceId(Long obj){
		this.resourceId = obj;
	}

	public Long getResourceId(){
		return resourceId;
	}

	public void setPhoneId(String obj){
		this.phoneId = obj;
	}

	public String getPhoneId(){
		return phoneId;
	}

	public void setCallScreenNoType(Integer obj){
		this.callScreenNoType = obj;
	}

	public Integer getCallScreenNoType(){
		return callScreenNoType;
	}

	public void setEffectTime(String obj){
		this.effectTime = obj;
	}

	public String getEffectTime(){
		return effectTime;
	}

	public void setExpireTime(String obj){
		this.expireTime = obj;
	}

	public String getExpireTime(){
		return expireTime;
	}

	public void setWeekStart(Integer obj){
		this.weekStart = obj;
	}

	public Integer getWeekStart(){
		return weekStart;
	}

	public void setWeekStop(Integer obj){
		this.weekStop = obj;
	}

	public Integer getWeekStop(){
		return weekStop;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setRouteNumber(String obj){
		this.routeNumber = obj;
	}

	public String getRouteNumber(){
		return routeNumber;
	}

	public void setIrRouteFlag(Integer obj){
		this.irRouteFlag = obj;
	}

	public Integer getIrRouteFlag(){
		return irRouteFlag;
	}

	public void setRoutingMethod(Integer obj){
		this.routingMethod = obj;
	}

	public Integer getRoutingMethod(){
		return routingMethod;
	}

	public void setListType(Integer obj){
		this.listType = obj;
	}

	public Integer getListType(){
		return listType;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setSoDate(Date obj){
		this.soDate = obj;
	}

	public Date getSoDate(){
		return soDate;
	}

	public CmResLastIcs(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CmResLastIcs rhs=(CmResLastIcs)rhs0;
		if(!ObjectUtils.equals(resourceId, rhs.resourceId)) return false;
		if(!ObjectUtils.equals(phoneId, rhs.phoneId)) return false;
		if(!ObjectUtils.equals(callScreenNoType, rhs.callScreenNoType)) return false;
		if(!ObjectUtils.equals(effectTime, rhs.effectTime)) return false;
		if(!ObjectUtils.equals(expireTime, rhs.expireTime)) return false;
		if(!ObjectUtils.equals(weekStart, rhs.weekStart)) return false;
		if(!ObjectUtils.equals(weekStop, rhs.weekStop)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(routeNumber, rhs.routeNumber)) return false;
		if(!ObjectUtils.equals(irRouteFlag, rhs.irRouteFlag)) return false;
		if(!ObjectUtils.equals(routingMethod, rhs.routingMethod)) return false;
		if(!ObjectUtils.equals(listType, rhs.listType)) return false;
		if(!ObjectUtils.equals(createDate, rhs.createDate)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(soDate, rhs.soDate)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(resourceId)
		.append(phoneId)
		.append(callScreenNoType)
		.append(effectTime)
		.append(expireTime)
		.append(weekStart)
		.append(weekStop)
		.append(expireDate)
		.append(routeNumber)
		.append(irRouteFlag)
		.append(routingMethod)
		.append(listType)
		.append(createDate)
		.append(validDate)
		.append(soNbr)
		.append(soDate)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{resourceId,phoneId,callScreenNoType,effectTime,expireTime,weekStart,weekStop,expireDate,routeNumber,irRouteFlag,routingMethod,listType,createDate,validDate,soNbr,soDate}
}