package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@Entity
@Table(schema="CD",name="CM_USER_ORDER")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"resourceId","busiType","msisdn","servType","spCode","operatorCode","thirdMsisdn","property","regionCode","orderSts","hisFirstOrderTime","changeTime","firstOrderTime","lastOrderTime","srcType","extendFlag","isNew","subType","serviceCode","createDate","soDate","soNbr","validDate","expireDate","productId","thirdResourceId","bizTypeCode","billType","instId","relInsId"})
public class CmUserOrder extends DataObject{


	@Column(name="RESOURCE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="resourceId")
	private Long resourceId;

	@Column(name="BUSI_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="busiType")
	private Integer busiType;

	@Column(name="MSISDN",columnDefinition="Varchar",length=64)
	@XmlElement(name="msisdn")
	private String msisdn;

	@Column(name="SERV_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="servType")
	private Integer servType;

	@Column(name="SP_CODE",columnDefinition="Varchar",length=32)
	@XmlElement(name="spCode")
	private String spCode;

	@Column(name="OPERATOR_CODE",columnDefinition="Varchar",length=32)
	@XmlElement(name="operatorCode")
	private String operatorCode;

	@Column(name="THIRD_MSISDN",columnDefinition="Varchar",length=15)
	@XmlElement(name="thirdMsisdn")
	private String thirdMsisdn;

	@Column(name="PROPERTY",columnDefinition="Varchar",length=20)
	@XmlElement(name="property")
	private String property;

	@Column(name="REGION_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="regionCode")
	private Integer regionCode;

	@Column(name="ORDER_STS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="orderSts")
	private Integer orderSts;

	@Column(name="HIS_FIRST_ORDER_TIME",columnDefinition="TimeStamp")
	@XmlElement(name="hisFirstOrderTime")
	private Date hisFirstOrderTime;

	@Column(name="CHANGE_TIME",columnDefinition="TimeStamp")
	@XmlElement(name="changeTime")
	private Date changeTime;

	@Column(name="FIRST_ORDER_TIME",columnDefinition="TimeStamp")
	@XmlElement(name="firstOrderTime")
	private Date firstOrderTime;

	@Column(name="LAST_ORDER_TIME",columnDefinition="TimeStamp")
	@XmlElement(name="lastOrderTime")
	private Date lastOrderTime;

	@Column(name="SRC_TYPE",columnDefinition="Varchar",length=64)
	@XmlElement(name="srcType")
	private String srcType;

	@Column(name="EXTEND_FLAG",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="extendFlag")
	private Integer extendFlag;

	@Column(name="IS_NEW",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="isNew")
	private Integer isNew;

	@Column(name="SUB_TYPE",columnDefinition="Varchar",length=4)
	@XmlElement(name="subType")
	private String subType;

	@Column(name="SERVICE_CODE",columnDefinition="Varchar",length=32)
	@XmlElement(name="serviceCode")
	private String serviceCode;

	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	@Column(name="SO_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="soDate")
	private Date soDate;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Id
	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="PRODUCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="productId")
	private Long productId;

	@Column(name="THIRD_RESOURCE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="thirdResourceId")
	private Long thirdResourceId;

	@Column(name="BIZ_TYPE_CODE",columnDefinition="Varchar",length=2)
	@XmlElement(name="bizTypeCode")
	private String bizTypeCode;

	@Column(name="BILL_TYPE",columnDefinition="Varchar",length=2)
	@XmlElement(name="billType")
	private String billType;

	@Id
	@Column(name="INST_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="instId")
	private Long instId;
	
	
	@Column(name="REL_INS_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="relInsId")
	private Long relInsId;

	public void setResourceId(Long obj){
		this.resourceId = obj;
	}

	public Long getResourceId(){
		return resourceId;
	}

	public void setBusiType(Integer obj){
		this.busiType = obj;
	}

	public Integer getBusiType(){
		return busiType;
	}

	public void setMsisdn(String obj){
		this.msisdn = obj;
	}

	public String getMsisdn(){
		return msisdn;
	}

	public void setServType(Integer obj){
		this.servType = obj;
	}

	public Integer getServType(){
		return servType;
	}

	public void setSpCode(String obj){
		this.spCode = obj;
	}

	public String getSpCode(){
		return spCode;
	}

	public void setOperatorCode(String obj){
		this.operatorCode = obj;
	}

	public String getOperatorCode(){
		return operatorCode;
	}

	public void setThirdMsisdn(String obj){
		this.thirdMsisdn = obj;
	}

	public String getThirdMsisdn(){
		return thirdMsisdn;
	}

	public void setProperty(String obj){
		this.property = obj;
	}

	public String getProperty(){
		return property;
	}

	public void setRegionCode(Integer obj){
		this.regionCode = obj;
	}

	public Integer getRegionCode(){
		return regionCode;
	}

	public void setOrderSts(Integer obj){
		this.orderSts = obj;
	}

	public Integer getOrderSts(){
		return orderSts;
	}

	public void setHisFirstOrderTime(Date obj){
		this.hisFirstOrderTime = obj;
	}

	public Date getHisFirstOrderTime(){
		return hisFirstOrderTime;
	}

	public void setChangeTime(Date obj){
		this.changeTime = obj;
	}

	public Date getChangeTime(){
		return changeTime;
	}

	public void setFirstOrderTime(Date obj){
		this.firstOrderTime = obj;
	}

	public Date getFirstOrderTime(){
		return firstOrderTime;
	}

	public void setLastOrderTime(Date obj){
		this.lastOrderTime = obj;
	}

	public Date getLastOrderTime(){
		return lastOrderTime;
	}

	public void setSrcType(String obj){
		this.srcType = obj;
	}

	public String getSrcType(){
		return srcType;
	}

	public void setExtendFlag(Integer obj){
		this.extendFlag = obj;
	}

	public Integer getExtendFlag(){
		return extendFlag;
	}

	public void setIsNew(Integer obj){
		this.isNew = obj;
	}

	public Integer getIsNew(){
		return isNew;
	}

	public void setSubType(String obj){
		this.subType = obj;
	}

	public String getSubType(){
		return subType;
	}

	public void setServiceCode(String obj){
		this.serviceCode = obj;
	}

	public String getServiceCode(){
		return serviceCode;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setSoDate(Date obj){
		this.soDate = obj;
	}

	public Date getSoDate(){
		return soDate;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setProductId(Long obj){
		this.productId = obj;
	}

	public Long getProductId(){
		return productId;
	}

	public void setThirdResourceId(Long obj){
		this.thirdResourceId = obj;
	}

	public Long getThirdResourceId(){
		return thirdResourceId;
	}

	public void setBizTypeCode(String obj){
		this.bizTypeCode = obj;
	}

	public String getBizTypeCode(){
		return bizTypeCode;
	}

	public void setBillType(String obj){
		this.billType = obj;
	}

	public String getBillType(){
		return billType;
	}

	public void setInstId(Long obj){
		this.instId = obj;
	}

	public Long getInstId(){
		return instId;
	}
	
	public Long getRelInsId() {
		return relInsId;
	}

	public void setRelInsId(Long relInsId) {
		this.relInsId = relInsId;
	}

	public CmUserOrder(){
	}

	public CmUserOrder(Date validDate,Long instId){
		this.validDate = validDate;
		this.instId = instId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CmUserOrder rhs=(CmUserOrder)rhs0;
		if(!ObjectUtils.equals(instId, rhs.instId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(instId)
		.append(validDate)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{resourceId,busiType,msisdn,servType,spCode,operatorCode,thirdMsisdn,property,regionCode,orderSts,hisFirstOrderTime,changeTime,firstOrderTime,lastOrderTime,srcType,extendFlag,isNew,subType,serviceCode,createDate,soDate,soNbr,validDate,expireDate,productId,thirdResourceId,bizTypeCode,billType,instId,relInsId}
}