package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="cd",name="CM_USER_VALIDCHANGE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"userId","validDate","expireDate","updateTime","updateStaffId","updateDepartId","remark","rsrvNum1","rsrvNum2","rsrvNum3","rsrvNum4","rsrvNum5","rsrvStr1","rsrvStr2","rsrvStr3","rsrvStr4","rsrvStr5","rsrvDate1","rsrvDate2","rsrvDate3","rsrvTag1","rsrvTag2","rsrvTag3","soNbr","soDate"})
public class CmUserValidchange extends DataObject{


	@Id
	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="userId")
	private Long userId;

	@Id
	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="UPDATE_TIME",columnDefinition="TimeStamp")
	@XmlElement(name="updateTime")
	private Date updateTime;

	@Column(name="UPDATE_STAFF_ID",columnDefinition="Char",length=8)
	@XmlElement(name="updateStaffId")
	private String updateStaffId;

	@Column(name="UPDATE_DEPART_ID",columnDefinition="Char",length=5)
	@XmlElement(name="updateDepartId")
	private String updateDepartId;

	@Column(name="REMARK",columnDefinition="Varchar",length=100)
	@XmlElement(name="remark")
	private String remark;

	@Column(name="RSRV_NUM1",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="rsrvNum1")
	private Integer rsrvNum1;

	@Column(name="RSRV_NUM2",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="rsrvNum2")
	private Integer rsrvNum2;

	@Column(name="RSRV_NUM3",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="rsrvNum3")
	private Integer rsrvNum3;

	@Column(name="RSRV_NUM4",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="rsrvNum4")
	private Long rsrvNum4;

	@Column(name="RSRV_NUM5",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="rsrvNum5")
	private Long rsrvNum5;

	@Column(name="RSRV_STR1",columnDefinition="Varchar",length=100)
	@XmlElement(name="rsrvStr1")
	private String rsrvStr1;

	@Column(name="RSRV_STR2",columnDefinition="Varchar",length=100)
	@XmlElement(name="rsrvStr2")
	private String rsrvStr2;

	@Column(name="RSRV_STR3",columnDefinition="Varchar",length=100)
	@XmlElement(name="rsrvStr3")
	private String rsrvStr3;

	@Column(name="RSRV_STR4",columnDefinition="Varchar",length=200)
	@XmlElement(name="rsrvStr4")
	private String rsrvStr4;

	@Column(name="RSRV_STR5",columnDefinition="Varchar",length=200)
	@XmlElement(name="rsrvStr5")
	private String rsrvStr5;

	@Column(name="RSRV_DATE1",columnDefinition="TimeStamp")
	@XmlElement(name="rsrvDate1")
	private Date rsrvDate1;

	@Column(name="RSRV_DATE2",columnDefinition="TimeStamp")
	@XmlElement(name="rsrvDate2")
	private Date rsrvDate2;

	@Column(name="RSRV_DATE3",columnDefinition="TimeStamp")
	@XmlElement(name="rsrvDate3")
	private Date rsrvDate3;

	@Column(name="RSRV_TAG1",columnDefinition="Char",length=1)
	@XmlElement(name="rsrvTag1")
	private String rsrvTag1;

	@Column(name="RSRV_TAG2",columnDefinition="Char",length=1)
	@XmlElement(name="rsrvTag2")
	private String rsrvTag2;

	@Column(name="RSRV_TAG3",columnDefinition="Char",length=1)
	@XmlElement(name="rsrvTag3")
	private String rsrvTag3;

	@Id
	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="SO_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="soDate")
	private Date soDate;

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setUpdateTime(Date obj){
		this.updateTime = obj;
	}

	public Date getUpdateTime(){
		return updateTime;
	}

	public void setUpdateStaffId(String obj){
		this.updateStaffId = obj;
	}

	public String getUpdateStaffId(){
		return updateStaffId;
	}

	public void setUpdateDepartId(String obj){
		this.updateDepartId = obj;
	}

	public String getUpdateDepartId(){
		return updateDepartId;
	}

	public void setRemark(String obj){
		this.remark = obj;
	}

	public String getRemark(){
		return remark;
	}

	public void setRsrvNum1(Integer obj){
		this.rsrvNum1 = obj;
	}

	public Integer getRsrvNum1(){
		return rsrvNum1;
	}

	public void setRsrvNum2(Integer obj){
		this.rsrvNum2 = obj;
	}

	public Integer getRsrvNum2(){
		return rsrvNum2;
	}

	public void setRsrvNum3(Integer obj){
		this.rsrvNum3 = obj;
	}

	public Integer getRsrvNum3(){
		return rsrvNum3;
	}

	public void setRsrvNum4(Long obj){
		this.rsrvNum4 = obj;
	}

	public Long getRsrvNum4(){
		return rsrvNum4;
	}

	public void setRsrvNum5(Long obj){
		this.rsrvNum5 = obj;
	}

	public Long getRsrvNum5(){
		return rsrvNum5;
	}

	public void setRsrvStr1(String obj){
		this.rsrvStr1 = obj;
	}

	public String getRsrvStr1(){
		return rsrvStr1;
	}

	public void setRsrvStr2(String obj){
		this.rsrvStr2 = obj;
	}

	public String getRsrvStr2(){
		return rsrvStr2;
	}

	public void setRsrvStr3(String obj){
		this.rsrvStr3 = obj;
	}

	public String getRsrvStr3(){
		return rsrvStr3;
	}

	public void setRsrvStr4(String obj){
		this.rsrvStr4 = obj;
	}

	public String getRsrvStr4(){
		return rsrvStr4;
	}

	public void setRsrvStr5(String obj){
		this.rsrvStr5 = obj;
	}

	public String getRsrvStr5(){
		return rsrvStr5;
	}

	public void setRsrvDate1(Date obj){
		this.rsrvDate1 = obj;
	}

	public Date getRsrvDate1(){
		return rsrvDate1;
	}

	public void setRsrvDate2(Date obj){
		this.rsrvDate2 = obj;
	}

	public Date getRsrvDate2(){
		return rsrvDate2;
	}

	public void setRsrvDate3(Date obj){
		this.rsrvDate3 = obj;
	}

	public Date getRsrvDate3(){
		return rsrvDate3;
	}

	public void setRsrvTag1(String obj){
		this.rsrvTag1 = obj;
	}

	public String getRsrvTag1(){
		return rsrvTag1;
	}

	public void setRsrvTag2(String obj){
		this.rsrvTag2 = obj;
	}

	public String getRsrvTag2(){
		return rsrvTag2;
	}

	public void setRsrvTag3(String obj){
		this.rsrvTag3 = obj;
	}

	public String getRsrvTag3(){
		return rsrvTag3;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setSoDate(Date obj){
		this.soDate = obj;
	}

	public Date getSoDate(){
		return soDate;
	}

	public CmUserValidchange(){
	}

	public CmUserValidchange(Long userId,Date validDate,Long soNbr){
		this.userId = userId;
		this.validDate = validDate;
		this.soNbr = soNbr;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CmUserValidchange rhs=(CmUserValidchange)rhs0;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(validDate)
		.append(userId)
		.append(soNbr)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{userId,validDate,expireDate,updateTime,updateStaffId,updateDepartId,remark,rsrvNum1,rsrvNum2,rsrvNum3,rsrvNum4,rsrvNum5,rsrvStr1,rsrvStr2,rsrvStr3,rsrvStr4,rsrvStr5,rsrvDate1,rsrvDate2,rsrvDate3,rsrvTag1,rsrvTag2,rsrvTag3,soNbr,soDate}
}