package com.ailk.openbilling.persistence.cust.entity;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import jef.database.DataObject;

import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;


/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@Entity
@Table(schema="jd",name="I_USER_SVC_INT")
@XmlAccessorType(XmlAccessType.PROPERTY)
@XmlType(propOrder={"userId","userIdA","packageId","serviceId","mainTag","startDate","endDate","updateTime"})
public class CmUserSvcInt extends DataObject{


	@Column(name="USER_ID",scale=10,columnDefinition="NUMBER")
	private long userId;

	@Column(name="USER_ID_A",scale=10,columnDefinition="NUMBER")
	private long userIdA;

	@Column(name="PACKAGE_ID",scale=10,columnDefinition="NUMBER")
	private long packageId;

	@Column(name="SERVICE_ID",scale=10,columnDefinition="NUMBER")
	private long serviceId;

	@Column(name="MAIN_TAG",columnDefinition="Varchar",length=1)
	private String mainTag;

	@Column(name="START_DATE",columnDefinition="TimeStamp")
	private Date startDate;

	@Column(name="END_DATE",columnDefinition="TimeStamp")
	private Date endDate;

	@Column(name="UPDATE_TIME",columnDefinition="TimeStamp")
	private Date updateTime;
	
	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	private Date expireDate;

	@Column(name="OPER_TYPE",scale=10,columnDefinition="NUMBER")
	private Integer operType;

	@Column(name="SO_NBR",scale=10,columnDefinition="NUMBER")
	private Long soNbr;

	@Column(name="COMMIT_DATE",columnDefinition="TimeStamp")
	private Date commitDate;

	public void setUserId(Long obj){
		this.userId = obj;
	}

	@XmlElement(name="userId")
	public long getUserId(){
		return userId;
	}

	
	@XmlElement(name="userIdA")
	public long getUserIdA() {
		return userIdA;
	}

	public void setUserIdA(long userIdA) {
		this.userIdA = userIdA;
	}
	
	@XmlElement(name="packageId")
	public long getPackageId() {
		return packageId;
	}

	public void setPackageId(long packageId) {
		this.packageId = packageId;
	}

	@XmlElement(name="serviceId")
	public long getServiceId() {
		return serviceId;
	}

	public void setServiceId(long serviceId) {
		this.serviceId = serviceId;
	}
	
	@XmlElement(name="mainTag")
	public String getMainTag() {
		return mainTag;
	}

	public void setMainTag(String mainTag) {
		this.mainTag = mainTag;
	}
	
	@XmlElement(name="startDate")
	public Date getStartDate() {
		return startDate;
	}
	
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}
	
	@XmlElement(name="endDate")
	public Date getEndDate() {
		return endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	
	@XmlElement(name="updateTime")
	public Date getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
	
	
	@XmlElement(name="validDate")
	public Date getValidDate() {
		return validDate;
	}

	public void setValidDate(Date validDate) {
		this.validDate = validDate;
	}

	@XmlElement(name="expireDate")
	public Date getExpireDate() {
		return expireDate;
	}

	public void setExpireDate(Date expireDate) {
		this.expireDate = expireDate;
	}
	
	@XmlElement(name="operType")
	public Integer getOperType() {
		return operType;
	}

	public void setOperType(Integer operType) {
		this.operType = operType;
	}
	
	@XmlElement(name="operType")
	public Long getSoNbr() {
		return soNbr;
	}

	public void setSoNbr(Long soNbr) {
		this.soNbr = soNbr;
	}
	
	@XmlElement(name="commitDate")
	public Date getCommitDate() {
		return commitDate;
	}

	public void setCommitDate(Date commitDate) {
		this.commitDate = commitDate;
	}

	public CmUserSvcInt(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null) {return false;}
		if (!(rhs0 instanceof CmUserSvcInt)) {return false;}
		CmUserSvcInt rhs=(CmUserSvcInt)rhs0;
		if (!ObjectUtils.equals(userId, rhs.userId)) {return false;}
		if (!ObjectUtils.equals(userIdA, rhs.userIdA)) {return false;}
		if (!ObjectUtils.equals(packageId, rhs.packageId)) {return false;}
		if (!ObjectUtils.equals(serviceId, rhs.serviceId)) {return false;}
		if (!ObjectUtils.equals(mainTag, rhs.mainTag)) {return false;}
		if (!ObjectUtils.equals(startDate, rhs.startDate)) {return false;}
		if (!ObjectUtils.equals(endDate, rhs.endDate)) {return false;}
		if (!ObjectUtils.equals(updateTime, rhs.updateTime)) {return false;}
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(userId)
		.append(userIdA)
		.append(packageId)
		.append(serviceId)
		.append(mainTag)
		.append(startDate)
		.append(endDate)
		.append(updateTime)
		.append(super.getHashCode())
		.toHashCode();
	}

	public enum Field implements jef.database.Field
	{
		userId, userIdA, packageId, serviceId, mainTag, startDate, endDate, updateTime
	}

	

	@Override
	public String toString() {
		return "IUserSvcInt [userId=" + userId + ", userIdA=" + userIdA
				+ ", packageId=" + packageId + ", serviceId=" + serviceId
				+ ", mainTag=" + mainTag + ", startDate=" + startDate
				+ ", endDate=" + endDate + ", updateTime=" + updateTime + "]";
	}

}