package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="cd",name="IMS_BAR_SERVICE_SYNC")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"id","workOrderType","action","acctId","userId","phoneId","busiServiceId","actionDate","reasonCode","soNbr","createDate","sts","serviceName","dealDate","errorMsg","errorCode","dealCount"})
public class ImsBarServiceSync extends DataObject{


	/**
	 * ?bos??sequence?????
	 */
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="id")
	private Long id;

	@Column(name="WORK_ORDER_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="workOrderType")
	private Integer workOrderType;

	@Column(name="ACTION",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="action")
	private Integer action;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="PHONE_ID",columnDefinition="Varchar",length=30,nullable=false)
	@XmlElement(name="phoneId")
	private String phoneId;

	@Column(name="BUSI_SERVICE_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="busiServiceId")
	private Integer busiServiceId;

	@Column(name="ACTION_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="actionDate")
	private Date actionDate;

	@Column(name="REASON_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="reasonCode")
	private Integer reasonCode;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="soNbr")
	private Long soNbr;

	/**
	 * create date
	 */
	@Column(name="CREATE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="createDate")
	private Date createDate;

	/**
	 * 1:???? 2: ???
	 */
	@Column(name="STS",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="sts")
	private Integer sts;

	@Column(name="SERVICE_NAME",columnDefinition="Varchar",length=100)
	@XmlElement(name="serviceName")
	private String serviceName;

	@Column(name="DEAL_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealDate")
	private Date dealDate;

	@Column(name="ERROR_MSG",columnDefinition="Varchar",length=256)
	@XmlElement(name="errorMsg")
	private String errorMsg;

	@Column(name="ERROR_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="errorCode")
	private Integer errorCode;

	@Column(name="DEAL_COUNT",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="dealCount")
	private Integer dealCount;

	public void setId(Long obj){
		this.id = obj;
	}

	public Long getId(){
		return id;
	}

	public void setWorkOrderType(Integer obj){
		this.workOrderType = obj;
	}

	public Integer getWorkOrderType(){
		return workOrderType;
	}

	public void setAction(Integer obj){
		this.action = obj;
	}

	public Integer getAction(){
		return action;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setPhoneId(String obj){
		this.phoneId = obj;
	}

	public String getPhoneId(){
		return phoneId;
	}

	public void setBusiServiceId(Integer obj){
		this.busiServiceId = obj;
	}

	public Integer getBusiServiceId(){
		return busiServiceId;
	}

	public void setActionDate(Date obj){
		this.actionDate = obj;
	}

	public Date getActionDate(){
		return actionDate;
	}

	public void setReasonCode(Integer obj){
		this.reasonCode = obj;
	}

	public Integer getReasonCode(){
		return reasonCode;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setSts(Integer obj){
		this.sts = obj;
	}

	public Integer getSts(){
		return sts;
	}

	public void setServiceName(String obj){
		this.serviceName = obj;
	}

	public String getServiceName(){
		return serviceName;
	}

	public void setDealDate(Date obj){
		this.dealDate = obj;
	}

	public Date getDealDate(){
		return dealDate;
	}

	public void setErrorMsg(String obj){
		this.errorMsg = obj;
	}

	public String getErrorMsg(){
		return errorMsg;
	}

	public void setErrorCode(Integer obj){
		this.errorCode = obj;
	}

	public Integer getErrorCode(){
		return errorCode;
	}

	public void setDealCount(Integer obj){
		this.dealCount = obj;
	}

	public Integer getDealCount(){
		return dealCount;
	}

	public ImsBarServiceSync(){
	}

	public ImsBarServiceSync(Long id){
		this.id = id;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		ImsBarServiceSync rhs=(ImsBarServiceSync)rhs0;
		if(!ObjectUtils.equals(id, rhs.id)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(id)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{id,workOrderType,action,acctId,userId,phoneId,busiServiceId,actionDate,reasonCode,soNbr,createDate,sts,serviceName,dealDate,errorMsg,errorCode,dealCount}
}