package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="cd",name="IMS_CUST_PROD_SYNC")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"id","custId","acctId","userId","phoneId","activationTime","smsLanguage","ussdLanguage","ivrLanguage","actChannel","activeCac","expireDate","balanceBookItem","balanceAmount","balanceDays","balanceAcctId","balanceUserId","balancePhoneId","balanceValidDate","balanceExpireDate","balanceNegative","soNbr","createDate","sts","bosSoDate","bosSoNbr","errorMsg","errorCode","dealCount","dealDate"})
public class ImsCustProdSync extends DataObject{


	/**
	 * ?bos??sequence?????
	 */
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="id")
	private Long id;

	@Column(name="CUST_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="custId")
	private Long custId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="PHONE_ID",columnDefinition="Varchar",length=30)
	@XmlElement(name="phoneId")
	private String phoneId;

	@Column(name="ACTIVATION_TIME",columnDefinition="TimeStamp")
	@XmlElement(name="activationTime")
	private Date activationTime;

	@Column(name="SMS_LANGUAGE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="smsLanguage")
	private Integer smsLanguage;

	@Column(name="USSD_LANGUAGE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="ussdLanguage")
	private Integer ussdLanguage;

	@Column(name="IVR_LANGUAGE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="ivrLanguage")
	private Integer ivrLanguage;

	@Column(name="ACT_CHANNEL",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="actChannel")
	private Integer actChannel;

	@Column(name="ACTIVE_CAC",columnDefinition="Varchar",length=255)
	@XmlElement(name="activeCac")
	private String activeCac;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="BALANCE_BOOK_ITEM",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="balanceBookItem")
	private Integer balanceBookItem;

	@Column(name="BALANCE_AMOUNT",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="balanceAmount")
	private Long balanceAmount;

	@Column(name="BALANCE_DAYS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="balanceDays")
	private Integer balanceDays;

	@Column(name="BALANCE_ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="balanceAcctId")
	private Long balanceAcctId;

	@Column(name="BALANCE_USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="balanceUserId")
	private Long balanceUserId;

	@Column(name="BALANCE_PHONE_ID",columnDefinition="Varchar",length=30)
	@XmlElement(name="balancePhoneId")
	private String balancePhoneId;

	@Column(name="BALANCE_VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="balanceValidDate")
	private Date balanceValidDate;

	@Column(name="BALANCE_EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="balanceExpireDate")
	private Date balanceExpireDate;

	@Column(name="BALANCE_NEGATIVE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="balanceNegative")
	private Long balanceNegative;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	/**
	 * create date
	 */
	@Column(name="CREATE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="createDate")
	private Date createDate;

	/**
	 * 1:???? 2: ???
	 */
	@Column(name="STS",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="sts")
	private Integer sts;

	/**
	 * ??reward??????
	 */
	@Column(name="BOS_SO_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="bosSoDate")
	private Date bosSoDate;

	/**
	 * ??reward?????
	 */
	@Column(name="BOS_SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="bosSoNbr")
	private Long bosSoNbr;

	@Column(name="ERROR_MSG",columnDefinition="Varchar",length=256)
	@XmlElement(name="errorMsg")
	private String errorMsg;

	@Column(name="ERROR_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="errorCode")
	private Integer errorCode;

	@Column(name="DEAL_COUNT",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="dealCount")
	private Integer dealCount;

	@Column(name="DEAL_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealDate")
	private Date dealDate;

	public void setId(Long obj){
		this.id = obj;
	}

	public Long getId(){
		return id;
	}

	public void setCustId(Long obj){
		this.custId = obj;
	}

	public Long getCustId(){
		return custId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setPhoneId(String obj){
		this.phoneId = obj;
	}

	public String getPhoneId(){
		return phoneId;
	}

	public void setActivationTime(Date obj){
		this.activationTime = obj;
	}

	public Date getActivationTime(){
		return activationTime;
	}

	public void setSmsLanguage(Integer obj){
		this.smsLanguage = obj;
	}

	public Integer getSmsLanguage(){
		return smsLanguage;
	}

	public void setUssdLanguage(Integer obj){
		this.ussdLanguage = obj;
	}

	public Integer getUssdLanguage(){
		return ussdLanguage;
	}

	public void setIvrLanguage(Integer obj){
		this.ivrLanguage = obj;
	}

	public Integer getIvrLanguage(){
		return ivrLanguage;
	}

	public void setActChannel(Integer obj){
		this.actChannel = obj;
	}

	public Integer getActChannel(){
		return actChannel;
	}

	public void setActiveCac(String obj){
		this.activeCac = obj;
	}

	public String getActiveCac(){
		return activeCac;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setBalanceBookItem(Integer obj){
		this.balanceBookItem = obj;
	}

	public Integer getBalanceBookItem(){
		return balanceBookItem;
	}

	public void setBalanceAmount(Long obj){
		this.balanceAmount = obj;
	}

	public Long getBalanceAmount(){
		return balanceAmount;
	}

	public void setBalanceDays(Integer obj){
		this.balanceDays = obj;
	}

	public Integer getBalanceDays(){
		return balanceDays;
	}

	public void setBalanceAcctId(Long obj){
		this.balanceAcctId = obj;
	}

	public Long getBalanceAcctId(){
		return balanceAcctId;
	}

	public void setBalanceUserId(Long obj){
		this.balanceUserId = obj;
	}

	public Long getBalanceUserId(){
		return balanceUserId;
	}

	public void setBalancePhoneId(String obj){
		this.balancePhoneId = obj;
	}

	public String getBalancePhoneId(){
		return balancePhoneId;
	}

	public void setBalanceValidDate(Date obj){
		this.balanceValidDate = obj;
	}

	public Date getBalanceValidDate(){
		return balanceValidDate;
	}

	public void setBalanceExpireDate(Date obj){
		this.balanceExpireDate = obj;
	}

	public Date getBalanceExpireDate(){
		return balanceExpireDate;
	}

	public void setBalanceNegative(Long obj){
		this.balanceNegative = obj;
	}

	public Long getBalanceNegative(){
		return balanceNegative;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setSts(Integer obj){
		this.sts = obj;
	}

	public Integer getSts(){
		return sts;
	}

	public void setBosSoDate(Date obj){
		this.bosSoDate = obj;
	}

	public Date getBosSoDate(){
		return bosSoDate;
	}

	public void setBosSoNbr(Long obj){
		this.bosSoNbr = obj;
	}

	public Long getBosSoNbr(){
		return bosSoNbr;
	}

	public void setErrorMsg(String obj){
		this.errorMsg = obj;
	}

	public String getErrorMsg(){
		return errorMsg;
	}

	public void setErrorCode(Integer obj){
		this.errorCode = obj;
	}

	public Integer getErrorCode(){
		return errorCode;
	}

	public void setDealCount(Integer obj){
		this.dealCount = obj;
	}

	public Integer getDealCount(){
		return dealCount;
	}

	public void setDealDate(Date obj){
		this.dealDate = obj;
	}

	public Date getDealDate(){
		return dealDate;
	}

	public ImsCustProdSync(){
	}

	public ImsCustProdSync(Long id){
		this.id = id;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		ImsCustProdSync rhs=(ImsCustProdSync)rhs0;
		if(!ObjectUtils.equals(id, rhs.id)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(id)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{id,custId,acctId,userId,phoneId,activationTime,smsLanguage,ussdLanguage,ivrLanguage,actChannel,activeCac,expireDate,balanceBookItem,balanceAmount,balanceDays,balanceAcctId,balanceUserId,balancePhoneId,balanceValidDate,balanceExpireDate,balanceNegative,soNbr,createDate,sts,bosSoDate,bosSoNbr,errorMsg,errorCode,dealCount,dealDate}
}