package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="CD",name="IMS_EXPIRE_PROD_NOTIFY_RST")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"id","prodId","receivePhone","expireDate","createDate","dealDate","dealSts","dealDesc","dealAgainDate","custId","acctId","userId","offerId","validDate","notificationId","freeResFlag"})
public class ImsExpireProdNotifyRst extends DataObject{


	@Column(name="ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="id")
	private Long id;

	@Column(name="PROD_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="prodId")
	private Long prodId;

	@Column(name="RECEIVE_PHONE",columnDefinition="Varchar",length=64)
	@XmlElement(name="receivePhone")
	private String receivePhone;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	@Column(name="DEAL_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealDate")
	private Date dealDate;

	@Column(name="DEAL_STS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="dealSts")
	private Integer dealSts;

	@Column(name="DEAL_DESC",columnDefinition="Varchar",length=255)
	@XmlElement(name="dealDesc")
	private String dealDesc;

	@Column(name="DEAL_AGAIN_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealAgainDate")
	private Date dealAgainDate;

	@Column(name="CUST_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="custId")
	private Long custId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="OFFER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="offerId")
	private Long offerId;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="NOTIFICATION_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="notificationId")
	private Integer notificationId;

	@Column(name="FREE_RES_FLAG",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="freeResFlag")
	private Integer freeResFlag;

	public void setId(Long obj){
		this.id = obj;
	}

	public Long getId(){
		return id;
	}

	public void setProdId(Long obj){
		this.prodId = obj;
	}

	public Long getProdId(){
		return prodId;
	}

	public void setReceivePhone(String obj){
		this.receivePhone = obj;
	}

	public String getReceivePhone(){
		return receivePhone;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setDealDate(Date obj){
		this.dealDate = obj;
	}

	public Date getDealDate(){
		return dealDate;
	}

	public void setDealSts(Integer obj){
		this.dealSts = obj;
	}

	public Integer getDealSts(){
		return dealSts;
	}

	public void setDealDesc(String obj){
		this.dealDesc = obj;
	}

	public String getDealDesc(){
		return dealDesc;
	}

	public void setDealAgainDate(Date obj){
		this.dealAgainDate = obj;
	}

	public Date getDealAgainDate(){
		return dealAgainDate;
	}

	public void setCustId(Long obj){
		this.custId = obj;
	}

	public Long getCustId(){
		return custId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setOfferId(Long obj){
		this.offerId = obj;
	}

	public Long getOfferId(){
		return offerId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setNotificationId(Integer obj){
		this.notificationId = obj;
	}

	public Integer getNotificationId(){
		return notificationId;
	}

	public void setFreeResFlag(Integer obj){
		this.freeResFlag = obj;
	}

	public Integer getFreeResFlag(){
		return freeResFlag;
	}

	public ImsExpireProdNotifyRst(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		ImsExpireProdNotifyRst rhs=(ImsExpireProdNotifyRst)rhs0;
		if(!ObjectUtils.equals(id, rhs.id)) return false;
		if(!ObjectUtils.equals(prodId, rhs.prodId)) return false;
		if(!ObjectUtils.equals(receivePhone, rhs.receivePhone)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(createDate, rhs.createDate)) return false;
		if(!ObjectUtils.equals(dealDate, rhs.dealDate)) return false;
		if(!ObjectUtils.equals(dealSts, rhs.dealSts)) return false;
		if(!ObjectUtils.equals(dealDesc, rhs.dealDesc)) return false;
		if(!ObjectUtils.equals(dealAgainDate, rhs.dealAgainDate)) return false;
		if(!ObjectUtils.equals(custId, rhs.custId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(offerId, rhs.offerId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(notificationId, rhs.notificationId)) return false;
		if(!ObjectUtils.equals(freeResFlag, rhs.freeResFlag)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(id)
		.append(prodId)
		.append(receivePhone)
		.append(expireDate)
		.append(createDate)
		.append(dealDate)
		.append(dealSts)
		.append(dealDesc)
		.append(dealAgainDate)
		.append(custId)
		.append(acctId)
		.append(userId)
		.append(offerId)
		.append(validDate)
		.append(notificationId)
		.append(freeResFlag)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{id,prodId,receivePhone,expireDate,createDate,dealDate,dealSts,dealDesc,dealAgainDate,custId,acctId,userId,offerId,validDate,notificationId,freeResFlag}
}