package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="cd",name="IMS_EXPIRE_PROD_NOTIFY")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"id","prodId","receivePhone","expireDate","createDate","sts","custId","acctId","userId","offerId","validDate","notificationId","freeResFlag","dealDate","dealCount","errorCode","errorMsg"})
public class ImsExpireProdNotify extends DataObject{


	@Column(name="ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="id")
	private Long id;

	@Column(name="PROD_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="prodId")
	private Long prodId;

	@Column(name="RECEIVE_PHONE",columnDefinition="Varchar",length=64)
	@XmlElement(name="receivePhone")
	private String receivePhone;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	@Column(name="STS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="sts")
	private Integer sts;

	@Column(name="CUST_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="custId")
	private Long custId;

	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="USER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="userId")
	private Long userId;

	@Column(name="OFFER_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="offerId")
	private Long offerId;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="NOTIFICATION_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="notificationId")
	private Integer notificationId;

	@Column(name="FREE_RES_FLAG",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="freeResFlag")
	private Integer freeResFlag;

	@Column(name="DEAL_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealDate")
	private Date dealDate;

	@Column(name="DEAL_COUNT",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="dealCount")
	private Integer dealCount;

	@Column(name="ERROR_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="errorCode")
	private Integer errorCode;

	@Column(name="ERROR_MSG",columnDefinition="Varchar",length=256)
	@XmlElement(name="errorMsg")
	private String errorMsg;

	public void setId(Long obj){
		this.id = obj;
	}

	public Long getId(){
		return id;
	}

	public void setProdId(Long obj){
		this.prodId = obj;
	}

	public Long getProdId(){
		return prodId;
	}

	public void setReceivePhone(String obj){
		this.receivePhone = obj;
	}

	public String getReceivePhone(){
		return receivePhone;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setSts(Integer obj){
		this.sts = obj;
	}

	public Integer getSts(){
		return sts;
	}

	public void setCustId(Long obj){
		this.custId = obj;
	}

	public Long getCustId(){
		return custId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setUserId(Long obj){
		this.userId = obj;
	}

	public Long getUserId(){
		return userId;
	}

	public void setOfferId(Long obj){
		this.offerId = obj;
	}

	public Long getOfferId(){
		return offerId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setNotificationId(Integer obj){
		this.notificationId = obj;
	}

	public Integer getNotificationId(){
		return notificationId;
	}

	public void setFreeResFlag(Integer obj){
		this.freeResFlag = obj;
	}

	public Integer getFreeResFlag(){
		return freeResFlag;
	}

	public void setDealDate(Date obj){
		this.dealDate = obj;
	}

	public Date getDealDate(){
		return dealDate;
	}

	public void setDealCount(Integer obj){
		this.dealCount = obj;
	}

	public Integer getDealCount(){
		return dealCount;
	}

	public void setErrorCode(Integer obj){
		this.errorCode = obj;
	}

	public Integer getErrorCode(){
		return errorCode;
	}

	public void setErrorMsg(String obj){
		this.errorMsg = obj;
	}

	public String getErrorMsg(){
		return errorMsg;
	}

	public ImsExpireProdNotify(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		ImsExpireProdNotify rhs=(ImsExpireProdNotify)rhs0;
		if(!ObjectUtils.equals(id, rhs.id)) return false;
		if(!ObjectUtils.equals(prodId, rhs.prodId)) return false;
		if(!ObjectUtils.equals(receivePhone, rhs.receivePhone)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(createDate, rhs.createDate)) return false;
		if(!ObjectUtils.equals(sts, rhs.sts)) return false;
		if(!ObjectUtils.equals(custId, rhs.custId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(userId, rhs.userId)) return false;
		if(!ObjectUtils.equals(offerId, rhs.offerId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(notificationId, rhs.notificationId)) return false;
		if(!ObjectUtils.equals(freeResFlag, rhs.freeResFlag)) return false;
		if(!ObjectUtils.equals(dealDate, rhs.dealDate)) return false;
		if(!ObjectUtils.equals(dealCount, rhs.dealCount)) return false;
		if(!ObjectUtils.equals(errorCode, rhs.errorCode)) return false;
		if(!ObjectUtils.equals(errorMsg, rhs.errorMsg)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(id)
		.append(prodId)
		.append(receivePhone)
		.append(expireDate)
		.append(createDate)
		.append(sts)
		.append(custId)
		.append(acctId)
		.append(userId)
		.append(offerId)
		.append(validDate)
		.append(notificationId)
		.append(freeResFlag)
		.append(dealDate)
		.append(dealCount)
		.append(errorCode)
		.append(errorMsg)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{id,prodId,receivePhone,expireDate,createDate,sts,custId,acctId,userId,offerId,validDate,notificationId,freeResFlag,dealDate,dealCount,errorCode,errorMsg}
}