package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="CD",name="IMS_RES_LIFECYCLE_NOTIFY_RST")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"resourceId","nsts","psts","notifyDate","createDate","objectType","id","dealCount","dealDate","errorMsg","errorCode","sts"})
public class ImsResLifecycleNotifyRst extends DataObject{


	@Column(name="RESOURCE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="resourceId")
	private Long resourceId;

	@Column(name="NSTS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="nsts")
	private Integer nsts;

	@Column(name="PSTS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="psts")
	private Integer psts;

	/**
	 * ??????
	 */
	@Column(name="NOTIFY_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="notifyDate")
	private Date notifyDate;

	@Column(name="CREATE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="createDate")
	private Date createDate;

	/**
	 * 0:?? 1:??
	 */
	@Column(name="OBJECT_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="objectType")
	private Integer objectType;

	/**
	 * ???
	 */
	@Column(name="ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="id")
	private Long id;

	/**
	 * ????
	 */
	@Column(name="DEAL_COUNT",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="dealCount")
	private Integer dealCount;

	/**
	 * ????
	 */
	@Column(name="DEAL_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="dealDate")
	private Date dealDate;

	/**
	 * ????
	 */
	@Column(name="ERROR_MSG",columnDefinition="Varchar",length=256)
	@XmlElement(name="errorMsg")
	private String errorMsg;

	/**
	 * ????
	 */
	@Column(name="ERROR_CODE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="errorCode")
	private Integer errorCode;

	/**
	 * ??1:??2:????3:??
	 */
	@Column(name="STS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="sts")
	private Integer sts;

	public void setResourceId(Long obj){
		this.resourceId = obj;
	}

	public Long getResourceId(){
		return resourceId;
	}

	public void setNsts(Integer obj){
		this.nsts = obj;
	}

	public Integer getNsts(){
		return nsts;
	}

	public void setPsts(Integer obj){
		this.psts = obj;
	}

	public Integer getPsts(){
		return psts;
	}

	public void setNotifyDate(Date obj){
		this.notifyDate = obj;
	}

	public Date getNotifyDate(){
		return notifyDate;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setObjectType(Integer obj){
		this.objectType = obj;
	}

	public Integer getObjectType(){
		return objectType;
	}

	public void setId(Long obj){
		this.id = obj;
	}

	public Long getId(){
		return id;
	}

	public void setDealCount(Integer obj){
		this.dealCount = obj;
	}

	public Integer getDealCount(){
		return dealCount;
	}

	public void setDealDate(Date obj){
		this.dealDate = obj;
	}

	public Date getDealDate(){
		return dealDate;
	}

	public void setErrorMsg(String obj){
		this.errorMsg = obj;
	}

	public String getErrorMsg(){
		return errorMsg;
	}

	public void setErrorCode(Integer obj){
		this.errorCode = obj;
	}

	public Integer getErrorCode(){
		return errorCode;
	}

	public void setSts(Integer obj){
		this.sts = obj;
	}

	public Integer getSts(){
		return sts;
	}

	public ImsResLifecycleNotifyRst(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		ImsResLifecycleNotifyRst rhs=(ImsResLifecycleNotifyRst)rhs0;
		if(!ObjectUtils.equals(resourceId, rhs.resourceId)) return false;
		if(!ObjectUtils.equals(nsts, rhs.nsts)) return false;
		if(!ObjectUtils.equals(psts, rhs.psts)) return false;
		if(!ObjectUtils.equals(notifyDate, rhs.notifyDate)) return false;
		if(!ObjectUtils.equals(createDate, rhs.createDate)) return false;
		if(!ObjectUtils.equals(objectType, rhs.objectType)) return false;
		if(!ObjectUtils.equals(id, rhs.id)) return false;
		if(!ObjectUtils.equals(dealCount, rhs.dealCount)) return false;
		if(!ObjectUtils.equals(dealDate, rhs.dealDate)) return false;
		if(!ObjectUtils.equals(errorMsg, rhs.errorMsg)) return false;
		if(!ObjectUtils.equals(errorCode, rhs.errorCode)) return false;
		if(!ObjectUtils.equals(sts, rhs.sts)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(resourceId)
		.append(nsts)
		.append(psts)
		.append(notifyDate)
		.append(createDate)
		.append(objectType)
		.append(id)
		.append(dealCount)
		.append(dealDate)
		.append(errorMsg)
		.append(errorCode)
		.append(sts)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{resourceId,nsts,psts,notifyDate,createDate,objectType,id,dealCount,dealDate,errorMsg,errorCode,sts}
}