package com.ailk.imssh.common.flow.consts;

import com.ailk.ims.util.SysUtil;
import com.ailk.imssh.prod.cmp.ProdExCmp;

import jef.database.meta.MetaHolder;

/**
 * @Description:定义扫描流程中用到的常量
 * @author wangjt
 * @Date 2012-9-21
 */
public interface FlowConst {
	// int DATA_INDEX_SCAN_BEFORE_DATE =
	// SysUtil.getInt("DATA_INDEX_SCAN_BEFORE_DATE");
	int DATA_INDEX_SCAN_ONE_TIME_COUNT = SysUtil.getInt("DATA_INDEX_SCAN_ONE_TIME_COUNT");
	int DATA_INDEX_QUEUE_MAX_COUNT = SysUtil.getInt("DATA_INDEX_QUEUE_MAX_COUNT");
	int DATA_INDEX_DEAL_THREAD_COUNT = SysUtil.getInt("DATA_INDEX_DEAL_THREAD_COUNT");
	int DATA_INDEX_SUB_TABLE_COUNT = SysUtil.getInt("DATA_INDEX_SUB_TABLE_COUNT");
	// int BATCH_INDEX_SCAN_BEFORE_DATE =
	// SysUtil.getInt("BATCH_INDEX_SCAN_BEFORE_DATE");
	int BATCH_INDEX_SCAN_ONE_TIME_COUNT = SysUtil.getInt("BATCH_INDEX_SCAN_ONE_TIME_COUNT");
	int BATCH_INDEX_QUEUE_MAX_COUNT = SysUtil.getInt("BATCH_INDEX_QUEUE_MAX_COUNT");
	int BATCH_INDEX_DEAL_THREAD_COUNT = SysUtil.getInt("BATCH_INDEX_DEAL_THREAD_COUNT");
	int BATCH_INDEX_SUB_TABLE_COUNT = SysUtil.getInt("BATCH_INDEX_SUB_TABLE_COUNT");
	int MANUAL_DEAL_THREAD_COUNT = SysUtil.getInt("DATA_INDEX_DEAL_THREAD_COUNT",30);

	int FIRST_WAIT_SECOND = SysUtil.getInt("FIRST_WAIT_SECOND");// 第一次等待时间，默认5秒；
	int MULTIPLY_FACTOR = SysUtil.getInt("MULTIPLY_FACTOR");// 相乘系数，默认为3；
	int MAX_RETRY_TIME = SysUtil.getInt("MAX_RETRY_TIME");// 最大重试次数，默认为10；

	short DB_SUCC_STS_FALSE = 0;// 0，初始状态，为默认值
	short DB_SUCC_STS_TRUE = 1;// 1，该工单数据入库成功而上发mdb失败
	short DB_DEAL_SUCC = 9; //物理库处理成功，mdb还未处理
	short MDB_DEAL_SUCC = 8;//mdb处理成功
	
	// i表传入的永久信用科目编号
	int FOREVER_CREDIT_ITEM_ID = SysUtil.getInt("FOREVER_CREDIT_ITEM_ID");

	int BIG_CUST_BUSI_CODE = SysUtil.getInt("BIG_CUST_BUSI_CODE", -1);

	// 毫秒
	int DATA_INDEX_DISPATCH_SLEEP_TIME = SysUtil.getInt("DATA_INDEX_SLEEP_TIME", 1000);

	int MAN_PRODUCT_ID_PREFIX = SysUtil.getInt("MAN_PRODUCT_ID_PREFIX", 0);

	// 押金划拨处理程序延迟几分钟分发处理 默认配 -10
	int IMS_DEPOSIT_DELAY_MINUTES = SysUtil.getInt("IMS_DEPOSIT_DELAY_MINUTES", -10);
	// 押金划拨默认每月1日(出账日) 0-8点 不延迟分发 默认配8
	int IMS_DEPOSIT_CANCEL_DELAY_TIME = SysUtil.getInt("IMS_DEPOSIT_CANCEL_DELAY_TIME", 8);


	public static final String GET_ROUTER_MAIN_SQL = 
			"SELECT REGION_CODE,ACCT_ID,CUST_ID,VALID_DATE,EXPIRE_DATE from ZD.SYS_RT_ACCOUNT WHERE ACCT_ID=? AND VALID_DATE<=? AND (EXPIRE_DATE>? OR EXPIRE_DATE IS NULL)";

	public static final String GET_ROUTER_MAIN_BY_CUST_SQL = 
			"SELECT REGION_CODE,ACCT_ID,CUST_ID,VALID_DATE,EXPIRE_DATE from ZD.SYS_RT_ACCOUNT WHERE CUST_ID=?";

	public static final String GET_ROUTER_CUSTOMER_SQL = 
			"SELECT CUST_ID,ACCT_ID,VALID_DATE,EXPIRE_DATE from ZD.SYS_RT_CUSTOMER WHERE CUST_ID=?  AND VALID_DATE<=? AND (EXPIRE_DATE>? OR EXPIRE_DATE IS NULL)";

	public static final String GET_ROUTER_IDENTITY_BY_RESOURCE_SQL = 
			"SELECT IDENTITY_ID,ID_TYPE,RESOURCE_ID,VALID_DATE,EXPIRE_DATE from ZD.SYS_RT_IDENTITY WHERE RESOURCE_ID=? AND ID_TYPE=? AND VALID_DATE<=? AND (EXPIRE_DATE>? OR EXPIRE_DATE IS NULL)";
	
	public static final String GET_ROUTER_IDENTITY_SQL = 
			"SELECT IDENTITY_ID,ID_TYPE,RESOURCE_ID,VALID_DATE,EXPIRE_DATE from ZD.SYS_RT_IDENTITY WHERE IDENTITY_ID=? AND ID_TYPE=? AND VALID_DATE<=? AND (EXPIRE_DATE>? OR EXPIRE_DATE IS NULL)";

	public static final String GET_ROUTER_IDENTITY_WITH_TENANT_SQL = 
			"SELECT IDENTITY_ID,ID_TYPE,SOURCE_TYPE,TENANT_ID,RESOURCE_ID,VALID_DATE from ZD.SYS_RT_IDENTITY WHERE IDENTITY_ID=? AND ID_TYPE=? AND SOURCE_TYPE=? AND TENANT_ID=? AND VALID_DATE<=? AND (EXPIRE_DATE>? OR EXPIRE_DATE IS NULL)";

	public static final String GET_ROUTER_RESOURCE_SQL = 
			"SELECT RESOURCE_ID,ACCT_ID,UPDATE_VERSION,VALID_DATE,EXPIRE_DATE from ZD.SYS_RT_RESOURCE WHERE RESOURCE_ID=? AND VALID_DATE<=? AND (EXPIRE_DATE>? OR EXPIRE_DATE IS NULL)";

}
