package com.ailk.openbilling.persistence.cust.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="AD",name="CA_RESOURCE_INV")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"resourceId","summaryDeliver","deliverAddr","validDate","expireDate","soNbr"})
public class CaResourceInv extends DataObject{


	/**
	 * 用户编号
	 */
	@Id
	@Column(name="RESOURCE_ID",precision=15,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resourceId")
	private long resourceId;

	/**
	 * 邮寄方式SUMMARY_DELIVER，默认是32位全部为0的字符串，排列顺序从左到右，枚举值如下 位数 说明 1 电子邮件 2 彩信 3 短信 （剩余的留着做扩展）
	 */
	@Column(name="SUMMARY_DELIVER",precision=32,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="summaryDeliver")
	private String summaryDeliver;

	/**
	 * 寄送地址
	 */
	@Column(name="DELIVER_ADDR",columnDefinition="Varchar",length=512,nullable=false)
	@XmlElement(name="deliverAddr")
	private String deliverAddr;

	/**
	 * 生效时间
	 */
	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	/**
	 * 失效时间
	 */
	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="soNbr")
	private Long soNbr;

	public void setResourceId(long obj){
		this.resourceId = obj;
	}

	public long getResourceId(){
		return resourceId;
	}

	public void setSummaryDeliver(String obj){
		this.summaryDeliver = obj;
	}

	public String getSummaryDeliver(){
		return summaryDeliver;
	}

	public void setDeliverAddr(String obj){
		this.deliverAddr = obj;
	}

	public String getDeliverAddr(){
		return deliverAddr;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public CaResourceInv(){
	}

	public CaResourceInv(long resourceId){
		this.resourceId = resourceId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CaResourceInv rhs=(CaResourceInv)rhs0;
		if(!ObjectUtils.equals(resourceId, rhs.resourceId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(resourceId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{resourceId,summaryDeliver,deliverAddr,validDate,expireDate,soNbr}
}