package com.ailk.openbilling.persistence.sys.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="sd",name="SYS_ENUM_DATA")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"tableName","columnName","codeValue","cname","sortId","dispName","domainFlag","isUsed","remarks","codeValueType"})
public class SysEnumData extends DataObject{


	/**
	 * Table name
	 */
	@Id
	@Column(name="TABLE_NAME",columnDefinition="Varchar",length=30,nullable=false)
	@XmlElement(name="tableName")
	private String tableName;

	/**
	 * Column name
	 */
	@Id
	@Column(name="COLUMN_NAME",columnDefinition="Varchar",length=64,nullable=false)
	@XmlElement(name="columnName")
	private String columnName;

	/**
	 * Field value
	 */
	@Id
	@Column(name="CODE_VALUE",columnDefinition="Varchar",length=256,nullable=false)
	@XmlElement(name="codeValue")
	private String codeValue;

	/**
	 * Chinese name
	 */
	@Column(name="CNAME",columnDefinition="Varchar",length=256)
	@XmlElement(name="cname")
	private String cname;

	/**
	 * Sorting ID
	 */
	@Column(name="SORT_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="sortId")
	private Integer sortId;

	/**
	 * Displayed name
	 */
	@Column(name="DISP_NAME",columnDefinition="Varchar",length=256)
	@XmlElement(name="dispName")
	private String dispName;

	/**
	 * Domain identifier: used to classify big-size function module and indicate that specific parameter belongs to corresponding module.    For example,    AD: --- Account Domain    BD: --- Business Param Domain    CD: --- Customer Domain    PD: --- Product Domain
	 */
	@Column(name="DOMAIN_FLAG",columnDefinition="Varchar",length=4)
	@XmlElement(name="domainFlag")
	private String domainFlag;

	/**
	 * Parameter usage state:    0：Unuse    1：Use
	 */
	@Column(name="IS_USED",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="isUsed")
	private Integer isUsed;

	/**
	 * Parameter remark
	 */
	@Column(name="REMARKS",columnDefinition="Varchar",length=1024)
	@XmlElement(name="remarks")
	private String remarks;

	/**
	 * 1--Char    2--Number    3--Boolean    4--Date    5--Long    6--String        7--Double
	 */
	@Column(name="CODE_VALUE_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="codeValueType")
	private Integer codeValueType;

	public void setTableName(String obj){
		this.tableName = obj;
	}

	public String getTableName(){
		return tableName;
	}

	public void setColumnName(String obj){
		this.columnName = obj;
	}

	public String getColumnName(){
		return columnName;
	}

	public void setCodeValue(String obj){
		this.codeValue = obj;
	}

	public String getCodeValue(){
		return codeValue;
	}

	public void setCname(String obj){
		this.cname = obj;
	}

	public String getCname(){
		return cname;
	}

	public void setSortId(Integer obj){
		this.sortId = obj;
	}

	public Integer getSortId(){
		return sortId;
	}

	public void setDispName(String obj){
		this.dispName = obj;
	}

	public String getDispName(){
		return dispName;
	}

	public void setDomainFlag(String obj){
		this.domainFlag = obj;
	}

	public String getDomainFlag(){
		return domainFlag;
	}

	public void setIsUsed(Integer obj){
		this.isUsed = obj;
	}

	public Integer getIsUsed(){
		return isUsed;
	}

	public void setRemarks(String obj){
		this.remarks = obj;
	}

	public String getRemarks(){
		return remarks;
	}

	public void setCodeValueType(Integer obj){
		this.codeValueType = obj;
	}

	public Integer getCodeValueType(){
		return codeValueType;
	}

	public SysEnumData(){
	}

	public SysEnumData(String tableName,String columnName,String codeValue){
		this.tableName = tableName;
		this.columnName = columnName;
		this.codeValue = codeValue;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		SysEnumData rhs=(SysEnumData)rhs0;
		if(!ObjectUtils.equals(tableName, rhs.tableName)) return false;
		if(!ObjectUtils.equals(codeValue, rhs.codeValue)) return false;
		if(!ObjectUtils.equals(columnName, rhs.columnName)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(tableName)
		.append(codeValue)
		.append(columnName)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{tableName,columnName,codeValue,cname,sortId,dispName,domainFlag,isUsed,remarks,codeValueType}
}