package com.ailk.openbilling.persistence.sys.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="SD",name="SYS_GROUP_DEF")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"groupId","groupName","regionCode","customerClass","customerType","customerSegment","accountType","singleBalance","billingType","resType","resSegment","priority","validDate","expireDate"})
public class SysGroupDef extends DataObject{


	/**
	 * group ID
	 */
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="GROUP_ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="groupId")
	private Integer groupId;

	/**
	 * Group name
	 */
	@Column(name="GROUP_NAME",columnDefinition="Varchar",length=256,nullable=false)
	@XmlElement(name="groupName")
	private String groupName;

	@Column(name="REGION_CODE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="regionCode")
	private Integer regionCode;

	/**
	 * Customer Class 0:Person 1:Family 2:Group  -1: ignore
	 */
	@Column(name="CUSTOMER_CLASS",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="customerClass")
	private Integer customerClass;

	/**
	 * customer type -1---ignore
	 */
	@Column(name="CUSTOMER_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="customerType")
	private Integer customerType;

	/**
	 * customer classes -1---ignore
	 */
	@Column(name="CUSTOMER_SEGMENT",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="customerSegment")
	private Integer customerSegment;

	/**
	 * account type -1---ignore
	 */
	@Column(name="ACCOUNT_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="accountType")
	private Integer accountType;

	/**
	 * 0：相应配置不参考此字段；  1：参考此字段，相应用户属性必须配置为-1，如SYS_GROUP_DEF的BILLING_TYPE，RES_TYPE，BI_BUSI_AVAIBLE表的BRAND_ID，MAIN_PROMOTION等
	 */
	@Column(name="SINGLE_BALANCE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="singleBalance")
	private Integer singleBalance;

	/**
	 * billing type  -1-ignore
	 */
	@Column(name="BILLING_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="billingType")
	private Integer billingType;

	/**
	 * equipment type -1-ignore
	 */
	@Column(name="RES_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resType")
	private Integer resType;

	/**
	 * Resource segment 1.Classic 2.Gold 3.Platinum 4.Platinum Plus 5.Serenade CEO 6.Serenade Prestige 7.Standard
	 */
	@Column(name="RES_SEGMENT",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resSegment")
	private Integer resSegment;

	/**
	 * Priority Larger value, higher priority.
	 */
	@Column(name="PRIORITY",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="priority")
	private Integer priority;

	/**
	 * valid date
	 */
	@Column(name="VALID_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="validDate")
	private Date validDate;

	/**
	 * invalid date
	 */
	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="expireDate")
	private Date expireDate;

	public void setGroupId(Integer obj){
		this.groupId = obj;
	}

	public Integer getGroupId(){
		return groupId;
	}

	public void setGroupName(String obj){
		this.groupName = obj;
	}

	public String getGroupName(){
		return groupName;
	}

	public void setRegionCode(Integer obj){
		this.regionCode = obj;
	}

	public Integer getRegionCode(){
		return regionCode;
	}

	public void setCustomerClass(Integer obj){
		this.customerClass = obj;
	}

	public Integer getCustomerClass(){
		return customerClass;
	}

	public void setCustomerType(Integer obj){
		this.customerType = obj;
	}

	public Integer getCustomerType(){
		return customerType;
	}

	public void setCustomerSegment(Integer obj){
		this.customerSegment = obj;
	}

	public Integer getCustomerSegment(){
		return customerSegment;
	}

	public void setAccountType(Integer obj){
		this.accountType = obj;
	}

	public Integer getAccountType(){
		return accountType;
	}

	public void setSingleBalance(Integer obj){
		this.singleBalance = obj;
	}

	public Integer getSingleBalance(){
		return singleBalance;
	}

	public void setBillingType(Integer obj){
		this.billingType = obj;
	}

	public Integer getBillingType(){
		return billingType;
	}

	public void setResType(Integer obj){
		this.resType = obj;
	}

	public Integer getResType(){
		return resType;
	}

	public void setResSegment(Integer obj){
		this.resSegment = obj;
	}

	public Integer getResSegment(){
		return resSegment;
	}

	public void setPriority(Integer obj){
		this.priority = obj;
	}

	public Integer getPriority(){
		return priority;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public SysGroupDef(){
	}

	public SysGroupDef(Integer groupId){
		this.groupId = groupId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		SysGroupDef rhs=(SysGroupDef)rhs0;
		if(!ObjectUtils.equals(groupId, rhs.groupId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(groupId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{groupId,groupName,regionCode,customerClass,customerType,customerSegment,accountType,singleBalance,billingType,resType,resSegment,priority,validDate,expireDate}
}