package com.ailk.openbilling.persistence.sys.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="SD",name="SYS_GROUP_BILLING_PLAN")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"id","startDay","endDay","brandId","mainPromotion","policyId","cycleSpecId","billFormatId","regionCode","customerClass","customerType","customerSegment","accountType","billingType","resType"})
public class SysGroupBillingPlan extends DataObject{


	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="id")
	private Integer id;

	/**
	 * one day of calendar month
	 */
	@Column(name="START_DAY",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="startDay")
	private Integer startDay;

	/**
	 * one day of calendar month
	 */
	@Column(name="END_DAY",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="endDay")
	private Integer endDay;

	/**
	 * Brand ID
	 */
	@Column(name="BRAND_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="brandId")
	private Integer brandId;

	/**
	 * ฒฮฟผึ๗ฒ๚ฦทฃฌฤฌศฯ-1
	 */
	@Column(name="MAIN_PROMOTION",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="mainPromotion")
	private Integer mainPromotion;

	/**
	 * Policy ID, 0 for always true.
	 */
	@Column(name="POLICY_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="policyId")
	private Integer policyId;

	/**
	 * billing cycle specification ID
	 */
	@Column(name="CYCLE_SPEC_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="cycleSpecId")
	private Long cycleSpecId;

	/**
	 * bill format code
	 */
	@Column(name="BILL_FORMAT_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="billFormatId")
	private Integer billFormatId;

	@Column(name="REGION_CODE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="regionCode")
	private Integer regionCode;

	@Column(name="CUSTOMER_CLASS",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="customerClass")
	private Integer customerClass;

	@Column(name="CUSTOMER_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="customerType")
	private Integer customerType;

	@Column(name="CUSTOMER_SEGMENT",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="customerSegment")
	private Integer customerSegment;

	@Column(name="ACCOUNT_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="accountType")
	private Integer accountType;

	@Column(name="BILLING_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="billingType")
	private Integer billingType;

	@Column(name="RES_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resType")
	private Integer resType;

	public void setId(Integer obj){
		this.id = obj;
	}

	public Integer getId(){
		return id;
	}

	public void setStartDay(Integer obj){
		this.startDay = obj;
	}

	public Integer getStartDay(){
		return startDay;
	}

	public void setEndDay(Integer obj){
		this.endDay = obj;
	}

	public Integer getEndDay(){
		return endDay;
	}

	public void setBrandId(Integer obj){
		this.brandId = obj;
	}

	public Integer getBrandId(){
		return brandId;
	}

	public void setMainPromotion(Integer obj){
		this.mainPromotion = obj;
	}

	public Integer getMainPromotion(){
		return mainPromotion;
	}

	public void setPolicyId(Integer obj){
		this.policyId = obj;
	}

	public Integer getPolicyId(){
		return policyId;
	}

	public void setCycleSpecId(Long obj){
		this.cycleSpecId = obj;
	}

	public Long getCycleSpecId(){
		return cycleSpecId;
	}

	public void setBillFormatId(Integer obj){
		this.billFormatId = obj;
	}

	public Integer getBillFormatId(){
		return billFormatId;
	}

	public void setRegionCode(Integer obj){
		this.regionCode = obj;
	}

	public Integer getRegionCode(){
		return regionCode;
	}

	public void setCustomerClass(Integer obj){
		this.customerClass = obj;
	}

	public Integer getCustomerClass(){
		return customerClass;
	}

	public void setCustomerType(Integer obj){
		this.customerType = obj;
	}

	public Integer getCustomerType(){
		return customerType;
	}

	public void setCustomerSegment(Integer obj){
		this.customerSegment = obj;
	}

	public Integer getCustomerSegment(){
		return customerSegment;
	}

	public void setAccountType(Integer obj){
		this.accountType = obj;
	}

	public Integer getAccountType(){
		return accountType;
	}

	public void setBillingType(Integer obj){
		this.billingType = obj;
	}

	public Integer getBillingType(){
		return billingType;
	}

	public void setResType(Integer obj){
		this.resType = obj;
	}

	public Integer getResType(){
		return resType;
	}

	public SysGroupBillingPlan(){
	}

	public SysGroupBillingPlan(Integer id){
		this.id = id;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		SysGroupBillingPlan rhs=(SysGroupBillingPlan)rhs0;
		if(!ObjectUtils.equals(id, rhs.id)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(id)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{id,startDay,endDay,brandId,mainPromotion,policyId,cycleSpecId,billFormatId,regionCode,customerClass,customerType,customerSegment,accountType,billingType,resType}
}