package com.ailk.openbilling.persistence.sys.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="sd",name="SYS_MEASURE_EXCHANGE_RULE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"measureExchangeId","name","description"})
public class SysMeasureExchangeRule extends DataObject{


	/**
	 * Mersurement exchange identifier
	 */
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="MEASURE_EXCHANGE_ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="measureExchangeId")
	private Integer measureExchangeId;

	/**
	 * Name of measurement exchange
	 */
	@Column(name="NAME",columnDefinition="Varchar",length=256)
	@XmlElement(name="name")
	private String name;

	/**
	 * Measurement exchange rules specification
	 */
	@Column(name="DESCRIPTION",columnDefinition="Varchar",length=1024)
	@XmlElement(name="description")
	private String description;

	public void setMeasureExchangeId(Integer obj){
		this.measureExchangeId = obj;
	}

	public Integer getMeasureExchangeId(){
		return measureExchangeId;
	}

	public void setName(String obj){
		this.name = obj;
	}

	public String getName(){
		return name;
	}

	public void setDescription(String obj){
		this.description = obj;
	}

	public String getDescription(){
		return description;
	}

	public SysMeasureExchangeRule(){
	}

	public SysMeasureExchangeRule(Integer measureExchangeId){
		this.measureExchangeId = measureExchangeId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		SysMeasureExchangeRule rhs=(SysMeasureExchangeRule)rhs0;
		if(!ObjectUtils.equals(measureExchangeId, rhs.measureExchangeId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(measureExchangeId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{measureExchangeId,name,description}
}