package com.ailk.openbilling.persistence.pm.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="pd",name="PM_ALLOWANCE_REGULATION")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"allowanceRuleId","cycleUnit","cycleType","allowanceType"})
public class PmAllowanceRegulation extends DataObject{


	/**
	 * allowance regulation identifier
	 */
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="ALLOWANCE_RULE_ID",precision=9,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="allowanceRuleId")
	private int allowanceRuleId;

	/**
	 * cycle unit
	 */
	@Column(name="CYCLE_UNIT",precision=4,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="cycleUnit")
	private int cycleUnit;

	/**
	 * cycle type  1:calendar day cycle type 2:calendar week cycle type 3:calendar month cycle type 4:calendar year cycle type 5:dynamic month cycle type, similar function to add_months provided by ORACLE 6:shift calendar hour cycle type 7: shift calendar month cycle type calculate by days now, for calculation cycle, the minimun unit is day.
	 */
	@Column(name="CYCLE_TYPE",precision=4,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="cycleType")
	private int cycleType;

	@Column(name="ALLOWANCE_TYPE",precision=9,columnDefinition="NUMBER")
	@XmlElement(name="allowanceType")
	private Integer allowanceType;

	public void setAllowanceRuleId(int obj){
		this.allowanceRuleId = obj;
	}

	public int getAllowanceRuleId(){
		return allowanceRuleId;
	}

	public void setCycleUnit(int obj){
		this.cycleUnit = obj;
	}

	public int getCycleUnit(){
		return cycleUnit;
	}

	public void setCycleType(int obj){
		this.cycleType = obj;
	}

	public int getCycleType(){
		return cycleType;
	}

	public void setAllowanceType(Integer obj){
		this.allowanceType = obj;
	}

	public Integer getAllowanceType(){
		return allowanceType;
	}

	public PmAllowanceRegulation(){
	}

	public PmAllowanceRegulation(int allowanceRuleId){
		this.allowanceRuleId = allowanceRuleId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		PmAllowanceRegulation rhs=(PmAllowanceRegulation)rhs0;
		if(!ObjectUtils.equals(allowanceRuleId, rhs.allowanceRuleId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(allowanceRuleId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{allowanceRuleId,cycleUnit,cycleType,allowanceType}
}