package com.ailk.openbilling.persistence.pm.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="PD",name="PM_ALLOT_BUSI_CALC")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"busiType","productOfferingId","promType","numerator","denominator","bookRuleId"})
public class PmAllotBusiCalc extends DataObject{


	@Id
	@Column(name="BUSI_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="busiType")
	private Integer busiType;

	@Column(name="PRODUCT_OFFERING_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="productOfferingId")
	private Integer productOfferingId;

	@Id
	@Column(name="PROM_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="promType")
	private Integer promType;

	@Column(name="NUMERATOR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="numerator")
	private Integer numerator;

	@Column(name="DENOMINATOR",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="denominator")
	private Integer denominator;

	@Column(name="BOOK_RULE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="bookRuleId")
	private Integer bookRuleId;

	public void setBusiType(Integer obj){
		this.busiType = obj;
	}

	public Integer getBusiType(){
		return busiType;
	}

	public void setProductOfferingId(Integer obj){
		this.productOfferingId = obj;
	}

	public Integer getProductOfferingId(){
		return productOfferingId;
	}

	public void setPromType(Integer obj){
		this.promType = obj;
	}

	public Integer getPromType(){
		return promType;
	}

	public void setNumerator(Integer obj){
		this.numerator = obj;
	}

	public Integer getNumerator(){
		return numerator;
	}

	public void setDenominator(Integer obj){
		this.denominator = obj;
	}

	public Integer getDenominator(){
		return denominator;
	}

	public void setBookRuleId(Integer obj){
		this.bookRuleId = obj;
	}

	public Integer getBookRuleId(){
		return bookRuleId;
	}

	public PmAllotBusiCalc(){
	}

	public PmAllotBusiCalc(Integer busiType,Integer promType){
		this.busiType = busiType;
		this.promType = promType;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		PmAllotBusiCalc rhs=(PmAllotBusiCalc)rhs0;
		if(!ObjectUtils.equals(busiType, rhs.busiType)) return false;
		if(!ObjectUtils.equals(promType, rhs.promType)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(busiType)
		.append(promType)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{busiType,productOfferingId,promType,numerator,denominator,bookRuleId}
}