package com.ailk.openbilling.persistence.pm.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="PD",name="PM_CHANGE_OFFER_RULE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"id","priceRuleId","changeFlag","chargeValidity"})
public class PmChangeOfferRule extends DataObject{


	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="id")
	private Integer id;

	/**
	 * rating rule ID
	 */
	@Column(name="PRICE_RULE_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="priceRuleId")
	private Integer priceRuleId;

	/**
	 * 0:Change Promotion IN 1:Change Promotion OUT
	 */
	@Column(name="CHANGE_FLAG",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="changeFlag")
	private Integer changeFlag;

	/**
	 * 有效期天数减少到X天
	 */
	@Column(name="CHARGE_VALIDITY",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="chargeValidity")
	private Integer chargeValidity;

	public void setId(Integer obj){
		this.id = obj;
	}

	public Integer getId(){
		return id;
	}

	public void setPriceRuleId(Integer obj){
		this.priceRuleId = obj;
	}

	public Integer getPriceRuleId(){
		return priceRuleId;
	}

	public void setChangeFlag(Integer obj){
		this.changeFlag = obj;
	}

	public Integer getChangeFlag(){
		return changeFlag;
	}

	public void setChargeValidity(Integer obj){
		this.chargeValidity = obj;
	}

	public Integer getChargeValidity(){
		return chargeValidity;
	}

	public PmChangeOfferRule(){
	}

	public PmChangeOfferRule(Integer id){
		this.id = id;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		PmChangeOfferRule rhs=(PmChangeOfferRule)rhs0;
		if(!ObjectUtils.equals(id, rhs.id)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(id)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{id,priceRuleId,changeFlag,chargeValidity}
}