package com.ailk.openbilling.persistence.pm.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="pd",name="PM_COMPLEX_ACCUMULATE_PRICE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"priceId","accumulateItem","resAdjustFlag","optimalFlag"})
public class PmComplexAccumulatePrice extends DataObject{


	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="PRICE_ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="priceId")
	private Integer priceId;

	@Column(name="ACCUMULATE_ITEM",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="accumulateItem")
	private Integer accumulateItem;

	@Column(name="RES_ADJUST_FLAG",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="resAdjustFlag")
	private Integer resAdjustFlag;

	@Column(name="OPTIMAL_FLAG",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="optimalFlag")
	private Integer optimalFlag;

	public void setPriceId(Integer obj){
		this.priceId = obj;
	}

	public Integer getPriceId(){
		return priceId;
	}

	public void setAccumulateItem(Integer obj){
		this.accumulateItem = obj;
	}

	public Integer getAccumulateItem(){
		return accumulateItem;
	}

	public void setResAdjustFlag(Integer obj){
		this.resAdjustFlag = obj;
	}

	public Integer getResAdjustFlag(){
		return resAdjustFlag;
	}

	public void setOptimalFlag(Integer obj){
		this.optimalFlag = obj;
	}

	public Integer getOptimalFlag(){
		return optimalFlag;
	}

	public PmComplexAccumulatePrice(){
	}

	public PmComplexAccumulatePrice(Integer priceId){
		this.priceId = priceId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		PmComplexAccumulatePrice rhs=(PmComplexAccumulatePrice)rhs0;
		if(!ObjectUtils.equals(priceId, rhs.priceId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(priceId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{priceId,accumulateItem,resAdjustFlag,optimalFlag}
}