package com.ailk.openbilling.persistence.pm.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="PD",name="PM_COMPOSITE_RULE_PRICE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"pricingPlanId","priceRuleId","validDate","expireDate"})
public class PmCompositeRulePrice extends DataObject{


	/**
	 * Pricing Planing Identifier
	 */
	@Id
	@Column(name="PRICING_PLAN_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="pricingPlanId")
	private Integer pricingPlanId;

	/**
	 * Tariff package code, code rule is: $(pkg_type)+ unmeaning
	 */
	@Id
	@Column(name="PRICE_RULE_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="priceRuleId")
	private Integer priceRuleId;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="expireDate")
	private Date expireDate;

	public void setPricingPlanId(Integer obj){
		this.pricingPlanId = obj;
	}

	public Integer getPricingPlanId(){
		return pricingPlanId;
	}

	public void setPriceRuleId(Integer obj){
		this.priceRuleId = obj;
	}

	public Integer getPriceRuleId(){
		return priceRuleId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public PmCompositeRulePrice(){
	}

	public PmCompositeRulePrice(Integer pricingPlanId,Integer priceRuleId){
		this.pricingPlanId = pricingPlanId;
		this.priceRuleId = priceRuleId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		PmCompositeRulePrice rhs=(PmCompositeRulePrice)rhs0;
		if(!ObjectUtils.equals(priceRuleId, rhs.priceRuleId)) return false;
		if(!ObjectUtils.equals(pricingPlanId, rhs.pricingPlanId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(priceRuleId)
		.append(pricingPlanId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{pricingPlanId,priceRuleId,validDate,expireDate}
}