package com.ailk.openbilling.persistence.pm.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="pd",name="PM_COMPONENT_PRODOFFER_PRICE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"priceId","name","priceType","description","taxIncluded"})
public class PmComponentProdofferPrice extends DataObject{


	/**
	 * Pricing identifier, multiple pricing identifiers can be included in one pricing plan
	 */
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="PRICE_ID",precision=9,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="priceId")
	private int priceId;

	/**
	 * A short description of pricing name.
	 */
	@Column(name="NAME",columnDefinition="Varchar",length=256,nullable=false)
	@XmlElement(name="name")
	private String name;

	/**
	 * 0: Standard tariff 1: accumulate price 2: accumulate allowance 3: recurring  free resource 4:  one time free resource 5: discount on another discounted eligible charge 6: tax refund 7: recurring charge 8: billing discount 9: Handling Fee 10: 业务赠送 11: 业务累计
	 */
	@Column(name="PRICE_TYPE",precision=2,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="priceType")
	private int priceType;

	/**
	 * Detailed description of pricing
	 */
	@Column(name="DESCRIPTION",columnDefinition="Varchar",length=1024)
	@XmlElement(name="description")
	private String description;

	@Column(name="TAX_INCLUDED",precision=1,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="taxIncluded")
	private int taxIncluded;

	public void setPriceId(int obj){
		this.priceId = obj;
	}

	public int getPriceId(){
		return priceId;
	}

	public void setName(String obj){
		this.name = obj;
	}

	public String getName(){
		return name;
	}

	public void setPriceType(int obj){
		this.priceType = obj;
	}

	public int getPriceType(){
		return priceType;
	}

	public void setDescription(String obj){
		this.description = obj;
	}

	public String getDescription(){
		return description;
	}

	public void setTaxIncluded(int obj){
		this.taxIncluded = obj;
	}

	public int getTaxIncluded(){
		return taxIncluded;
	}

	public PmComponentProdofferPrice(){
	}

	public PmComponentProdofferPrice(int priceId){
		this.priceId = priceId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		PmComponentProdofferPrice rhs=(PmComponentProdofferPrice)rhs0;
		if(!ObjectUtils.equals(priceId, rhs.priceId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(priceId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{priceId,name,priceType,description,taxIncluded}
}