package com.ailk.openbilling.persistence.pm.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="PD",name="PM_FREE_USAGE_PROPERTY")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"assetItemId","measureId","carryForwardRuleId","consumeFlag","billingType","bonusUnitCycle"})
public class PmFreeUsageProperty extends DataObject{


	/**
	 * Free Resource Item ID
	 */
	@Id
	@Column(name="ASSET_ITEM_ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="assetItemId")
	private Integer assetItemId;

	/**
	 * Unit of Free Resource
	 */
	@Column(name="MEASURE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="measureId")
	private Integer measureId;

	/**
	 * Rule ID of one-time free resource CARRY FORWARD
	 */
	@Column(name="CARRY_FORWARD_RULE_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="carryForwardRuleId")
	private Integer carryForwardRuleId;

	/**
	 * Bill consumption indicate
Usage of free resource items
0: single item consumption
1: multiple items consumption
	 */
	@Column(name="CONSUME_FLAG",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="consumeFlag")
	private Integer consumeFlag;

	/**
	 * 免费资源付费方式
0.预付费prepaid only；
1.后付费postpaid only；
-1.不关注即prepaid & postpaid both
	 */
	@Column(name="BILLING_TYPE",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="billingType")
	private Integer billingType;

	/**
	 * 免费资源规整单位，一般按费率规整单位去规整。
举例：对于短信、梦网等按次业务的规整，单位一般配置成1。对于基本语音类业务的规整，一般配置成60。对于长途语音类业务的规整，一般配置成6
	 */
	@Column(name="BONUS_UNIT_CYCLE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="bonusUnitCycle")
	private Integer bonusUnitCycle;

	public void setAssetItemId(Integer obj){
		this.assetItemId = obj;
	}

	public Integer getAssetItemId(){
		return assetItemId;
	}

	public void setMeasureId(Integer obj){
		this.measureId = obj;
	}

	public Integer getMeasureId(){
		return measureId;
	}

	public void setCarryForwardRuleId(Integer obj){
		this.carryForwardRuleId = obj;
	}

	public Integer getCarryForwardRuleId(){
		return carryForwardRuleId;
	}

	public void setConsumeFlag(Integer obj){
		this.consumeFlag = obj;
	}

	public Integer getConsumeFlag(){
		return consumeFlag;
	}

	public void setBillingType(Integer obj){
		this.billingType = obj;
	}

	public Integer getBillingType(){
		return billingType;
	}

	public void setBonusUnitCycle(Integer obj){
		this.bonusUnitCycle = obj;
	}

	public Integer getBonusUnitCycle(){
		return bonusUnitCycle;
	}

	public PmFreeUsageProperty(){
	}

	public PmFreeUsageProperty(Integer assetItemId){
		this.assetItemId = assetItemId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		PmFreeUsageProperty rhs=(PmFreeUsageProperty)rhs0;
		if(!ObjectUtils.equals(assetItemId, rhs.assetItemId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(assetItemId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{assetItemId,measureId,carryForwardRuleId,consumeFlag,billingType,bonusUnitCycle}
}