package com.ailk.openbilling.persistence.pm.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="PD",name="PM_PRODUCT_OFFER_SPECIAL_ZONE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"productOfferingId","cellCode","validDate","expireDate","description","oppCellCode"})
public class PmProductOfferSpecialZone extends DataObject{


	/**
	 * Product offering Corresponding global promotion in special rate zone
	 */
	@Id
	@Column(name="PRODUCT_OFFERING_ID",precision=9,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="productOfferingId")
	private int productOfferingId;

	/**
	 * Zone code Define special rate zone in system level by visited location in table RS_SYS_CELL_INFO
	 */
	@Id
	@Column(name="CELL_CODE",precision=9,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="cellCode")
	private int cellCode;

	/**
	 * Effective date
	 */
	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	/**
	 * Expired date
	 */
	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	/**
	 * Description
	 */
	@Column(name="DESCRIPTION",columnDefinition="Varchar",length=1024)
	@XmlElement(name="description")
	private String description;

	@Id
	@Column(name="OPP_CELL_CODE",precision=9,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="oppCellCode")
	private int oppCellCode;

	public void setProductOfferingId(int obj){
		this.productOfferingId = obj;
	}

	public int getProductOfferingId(){
		return productOfferingId;
	}

	public void setCellCode(int obj){
		this.cellCode = obj;
	}

	public int getCellCode(){
		return cellCode;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setDescription(String obj){
		this.description = obj;
	}

	public String getDescription(){
		return description;
	}

	public void setOppCellCode(int obj){
		this.oppCellCode = obj;
	}

	public int getOppCellCode(){
		return oppCellCode;
	}

	public PmProductOfferSpecialZone(){
	}

	public PmProductOfferSpecialZone(int productOfferingId,int cellCode,int oppCellCode){
		this.productOfferingId = productOfferingId;
		this.cellCode = cellCode;
		this.oppCellCode = oppCellCode;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		PmProductOfferSpecialZone rhs=(PmProductOfferSpecialZone)rhs0;
		if(!ObjectUtils.equals(cellCode, rhs.cellCode)) return false;
		if(!ObjectUtils.equals(oppCellCode, rhs.oppCellCode)) return false;
		if(!ObjectUtils.equals(productOfferingId, rhs.productOfferingId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(cellCode)
		.append(oppCellCode)
		.append(productOfferingId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{productOfferingId,cellCode,validDate,expireDate,description,oppCellCode}
}