package com.ailk.openbilling.persistence.pm.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="pd",name="PM_PRODUCT_OFFER_ATTRIBUTE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"productOfferingId","policyId","billingType","suitableNet","availableSegId","probationCycleUnit","probationCycleType","probationEffectMod","offsetCycleType","offsetCycleUnit","isRefund","discountExpireMode"})
public class PmProductOfferAttribute extends DataObject{


	/**
	 * A unique identifier for the product offering.
	 */
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="PRODUCT_OFFERING_ID",precision=9,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="productOfferingId")
	private Integer productOfferingId;

	/**
	 * product offering effective condition, default 0
	 */
	@Column(name="POLICY_ID",precision=9,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="policyId")
	private Integer policyId;

	/**
	 * postpaid identifier for billing. for handling tariff in bills. According to the design of bill, example CO_PROD_BILLING_CYCLE is needed. 0-prepay 1-postpay
	 */
	@Column(name="BILLING_TYPE",precision=2,columnDefinition="NUMBER")
	@XmlElement(name="billingType")
	private Integer billingType;

	@Column(name="SUITABLE_NET",precision=4,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="suitableNet")
	private int suitableNet;

	@Column(name="AVAILABLE_SEG_ID",precision=4,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="availableSegId")
	private int availableSegId;

	@Column(name="PROBATION_CYCLE_UNIT",precision=4,columnDefinition="NUMBER")
	@XmlElement(name="probationCycleUnit")
	private Integer probationCycleUnit;

	@Column(name="PROBATION_CYCLE_TYPE",precision=4,columnDefinition="NUMBER")
	@XmlElement(name="probationCycleType")
	private Integer probationCycleType;

	@Column(name="PROBATION_EFFECT_MOD",precision=1,columnDefinition="NUMBER")
	@XmlElement(name="probationEffectMod")
	private Integer probationEffectMod;

	@Column(name="OFFSET_CYCLE_TYPE",precision=4,columnDefinition="NUMBER")
	@XmlElement(name="offsetCycleType")
	private Integer offsetCycleType;

	@Column(name="OFFSET_CYCLE_UNIT",precision=4,columnDefinition="NUMBER")
	@XmlElement(name="offsetCycleUnit")
	private Integer offsetCycleUnit;

	@Column(name="IS_REFUND",precision=1,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="isRefund")
	private Integer isRefund;

	@Column(name="DISCOUNT_EXPIRE_MODE",precision=4,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="discountExpireMode")
	private Integer discountExpireMode;

	public void setProductOfferingId(Integer obj){
		this.productOfferingId = obj;
	}

	public Integer getProductOfferingId(){
		return productOfferingId;
	}

	public void setPolicyId(Integer obj){
		this.policyId = obj;
	}

	public Integer getPolicyId(){
		return policyId;
	}

	public void setBillingType(Integer obj){
		this.billingType = obj;
	}

	public Integer getBillingType(){
		return billingType;
	}

	public void setSuitableNet(int obj){
		this.suitableNet = obj;
	}

	public int getSuitableNet(){
		return suitableNet;
	}

	public void setAvailableSegId(int obj){
		this.availableSegId = obj;
	}

	public int getAvailableSegId(){
		return availableSegId;
	}

	public void setProbationCycleUnit(Integer obj){
		this.probationCycleUnit = obj;
	}

	public Integer getProbationCycleUnit(){
		return probationCycleUnit;
	}

	public void setProbationCycleType(Integer obj){
		this.probationCycleType = obj;
	}

	public Integer getProbationCycleType(){
		return probationCycleType;
	}

	public void setProbationEffectMod(Integer obj){
		this.probationEffectMod = obj;
	}

	public Integer getProbationEffectMod(){
		return probationEffectMod;
	}

	public void setOffsetCycleType(Integer obj){
		this.offsetCycleType = obj;
	}

	public Integer getOffsetCycleType(){
		return offsetCycleType;
	}

	public void setOffsetCycleUnit(Integer obj){
		this.offsetCycleUnit = obj;
	}

	public Integer getOffsetCycleUnit(){
		return offsetCycleUnit;
	}

	public void setIsRefund(Integer obj){
		this.isRefund = obj;
	}

	public Integer getIsRefund(){
		return isRefund;
	}

	public void setDiscountExpireMode(Integer obj){
		this.discountExpireMode = obj;
	}

	public Integer getDiscountExpireMode(){
		return discountExpireMode;
	}

	public PmProductOfferAttribute(){
	}

	public PmProductOfferAttribute(Integer productOfferingId){
		this.productOfferingId = productOfferingId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		PmProductOfferAttribute rhs=(PmProductOfferAttribute)rhs0;
		if(!ObjectUtils.equals(productOfferingId, rhs.productOfferingId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(productOfferingId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{productOfferingId,policyId,billingType,suitableNet,availableSegId,probationCycleUnit,probationCycleType,probationEffectMod,offsetCycleType,offsetCycleUnit,isRefund,discountExpireMode}
}