package com.ailk.openbilling.persistence.acct.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="ad",name="BI_BUSI_AVAIBLE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"id","busiPlanId","brandId","mainPromotion","policyId","regionCode","customerClass","customerType","customerSegment","accountType","billingType","resType","resSegment","triggerServiceId","operatorId","balanceType"})
public class BiBusiAvaible extends DataObject{


	@Id
	@Column(name="ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="id")
	private Integer id;

	@Column(name="BUSI_PLAN_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="busiPlanId")
	private Integer busiPlanId;

	@Column(name="BRAND_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="brandId")
	private Integer brandId;

	@Column(name="MAIN_PROMOTION",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="mainPromotion")
	private Integer mainPromotion;

	@Column(name="POLICY_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="policyId")
	private Integer policyId;

	@Column(name="REGION_CODE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="regionCode")
	private Integer regionCode;

	@Column(name="CUSTOMER_CLASS",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="customerClass")
	private Integer customerClass;

	@Column(name="CUSTOMER_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="customerType")
	private Integer customerType;

	@Column(name="CUSTOMER_SEGMENT",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="customerSegment")
	private Integer customerSegment;

	@Column(name="ACCOUNT_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="accountType")
	private Integer accountType;

	@Column(name="BILLING_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="billingType")
	private Integer billingType;

	@Column(name="RES_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resType")
	private Integer resType;

	@Column(name="RES_SEGMENT",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resSegment")
	private Integer resSegment;

	@Column(name="TRIGGER_SERVICE_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="triggerServiceId")
	private Integer triggerServiceId;

	@Column(name="OPERATOR_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="operatorId")
	private Integer operatorId;

	@Column(name="BALANCE_TYPE",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="balanceType")
	private Integer balanceType;

	public void setId(Integer obj){
		this.id = obj;
	}

	public Integer getId(){
		return id;
	}

	public void setBusiPlanId(Integer obj){
		this.busiPlanId = obj;
	}

	public Integer getBusiPlanId(){
		return busiPlanId;
	}

	public void setBrandId(Integer obj){
		this.brandId = obj;
	}

	public Integer getBrandId(){
		return brandId;
	}

	public void setMainPromotion(Integer obj){
		this.mainPromotion = obj;
	}

	public Integer getMainPromotion(){
		return mainPromotion;
	}

	public void setPolicyId(Integer obj){
		this.policyId = obj;
	}

	public Integer getPolicyId(){
		return policyId;
	}

	public void setRegionCode(Integer obj){
		this.regionCode = obj;
	}

	public Integer getRegionCode(){
		return regionCode;
	}

	public void setCustomerClass(Integer obj){
		this.customerClass = obj;
	}

	public Integer getCustomerClass(){
		return customerClass;
	}

	public void setCustomerType(Integer obj){
		this.customerType = obj;
	}

	public Integer getCustomerType(){
		return customerType;
	}

	public void setCustomerSegment(Integer obj){
		this.customerSegment = obj;
	}

	public Integer getCustomerSegment(){
		return customerSegment;
	}

	public void setAccountType(Integer obj){
		this.accountType = obj;
	}

	public Integer getAccountType(){
		return accountType;
	}

	public void setBillingType(Integer obj){
		this.billingType = obj;
	}

	public Integer getBillingType(){
		return billingType;
	}

	public void setResType(Integer obj){
		this.resType = obj;
	}

	public Integer getResType(){
		return resType;
	}

	public void setResSegment(Integer obj){
		this.resSegment = obj;
	}

	public Integer getResSegment(){
		return resSegment;
	}

	public void setTriggerServiceId(Integer obj){
		this.triggerServiceId = obj;
	}

	public Integer getTriggerServiceId(){
		return triggerServiceId;
	}

	public void setOperatorId(Integer obj){
		this.operatorId = obj;
	}

	public Integer getOperatorId(){
		return operatorId;
	}

	public void setBalanceType(Integer obj){
		this.balanceType = obj;
	}

	public Integer getBalanceType(){
		return balanceType;
	}

	public BiBusiAvaible(){
	}

	public BiBusiAvaible(Integer id){
		this.id = id;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		BiBusiAvaible rhs=(BiBusiAvaible)rhs0;
		if(!ObjectUtils.equals(id, rhs.id)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(id)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{id,busiPlanId,brandId,mainPromotion,policyId,regionCode,customerClass,customerType,customerSegment,accountType,billingType,resType,resSegment,triggerServiceId,operatorId,balanceType}
}