package com.ailk.openbilling.persistence.acct.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="AD",name="CA_BILLING_PLAN_HIS")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"soNbr","soDate","billingPlanId","acctId","cycleSpecId","billFormatId","rangeSpecId","paymentPlanId","validDate","expireDate","createDate"})
public class CaBillingPlanHis extends DataObject{


	/**
	 * สภํนคตฅ
	 */
	@Id
	@Column(name="SO_NBR",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="soNbr")
	private Long soNbr;

	/**
	 * สภํสฑผไ
	 */
	@Column(name="SO_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="soDate")
	private Date soDate;

	/**
	 * ณ๖ีสผฦปฎฑเบล
	 */
	@Id
	@Column(name="BILLING_PLAN_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="billingPlanId")
	private Long billingPlanId;

	/**
	 * ีสปงฑเบล
	 */
	@Id
	@Column(name="ACCT_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="acctId")
	private Long acctId;

	/**
	 * ีสฦฺนๆธ๑ฑเบล
	 */
	@Column(name="CYCLE_SPEC_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="cycleSpecId")
	private Long cycleSpecId;

	/**
	 * ีสตฅธ๑สฝด๚ย๋
	 */
	@Column(name="BILL_FORMAT_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="billFormatId")
	private Integer billFormatId;

	/**
	 * ทถฮงนๆธ๑ฑเบล
	 */
	@Column(name="RANGE_SPEC_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="rangeSpecId")
	private Integer rangeSpecId;

	/**
	 * ึงธถผฦปฎฑเบล
	 */
	@Column(name="PAYMENT_PLAN_ID",precision=8,columnDefinition="NUMBER")
	@XmlElement(name="paymentPlanId")
	private Long paymentPlanId;

	/**
	 * ษ๚ะงฦฺ
	 */
	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	/**
	 * สงะงฦฺ
	 */
	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="expireDate")
	private Date expireDate;

	/**
	 * ตฑวฐผวยผตฤฒ๚ษ๚สฑผไ
	 */
	@Column(name="CREATE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="createDate")
	private Date createDate;

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setSoDate(Date obj){
		this.soDate = obj;
	}

	public Date getSoDate(){
		return soDate;
	}

	public void setBillingPlanId(Long obj){
		this.billingPlanId = obj;
	}

	public Long getBillingPlanId(){
		return billingPlanId;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setCycleSpecId(Long obj){
		this.cycleSpecId = obj;
	}

	public Long getCycleSpecId(){
		return cycleSpecId;
	}

	public void setBillFormatId(Integer obj){
		this.billFormatId = obj;
	}

	public Integer getBillFormatId(){
		return billFormatId;
	}

	public void setRangeSpecId(Integer obj){
		this.rangeSpecId = obj;
	}

	public Integer getRangeSpecId(){
		return rangeSpecId;
	}

	public void setPaymentPlanId(Long obj){
		this.paymentPlanId = obj;
	}

	public Long getPaymentPlanId(){
		return paymentPlanId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public CaBillingPlanHis(){
	}

	public CaBillingPlanHis(Long soNbr,Long billingPlanId,Long acctId){
		this.soNbr = soNbr;
		this.billingPlanId = billingPlanId;
		this.acctId = acctId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CaBillingPlanHis rhs=(CaBillingPlanHis)rhs0;
		if(!ObjectUtils.equals(billingPlanId, rhs.billingPlanId)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(billingPlanId)
		.append(acctId)
		.append(soNbr)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{soNbr,soDate,billingPlanId,acctId,cycleSpecId,billFormatId,rangeSpecId,paymentPlanId,validDate,expireDate,createDate}
}