package com.ailk.openbilling.persistence.acct.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(schema="AD",name="CA_CREDIT")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"assetId","creditItem","acctId","validDate","expireDate","createDate","creditAmount","measureId","billingType","soNbr","soDate","resourceId","creditFlag"})
public class CaCredit extends DataObject{


	@Column(name="ASSET_ID",precision=15,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="assetId")
	private Long assetId;

	@Column(name="CREDIT_ITEM",precision=9,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="creditItem")
	private Integer creditItem;

	@Column(name="ACCT_ID",precision=15,columnDefinition="NUMBER")
	@XmlElement(name="acctId")
	private Long acctId;

	@Column(name="VALID_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="validDate")
	private Date validDate;

	@Column(name="EXPIRE_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="expireDate")
	private Date expireDate;

	@Column(name="CREATE_DATE",columnDefinition="TimeStamp",nullable=false)
	@XmlElement(name="createDate")
	private Date createDate;

	@Column(name="CREDIT_AMOUNT",precision=12,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="creditAmount")
	private Long creditAmount;

	@Column(name="MEASURE_ID",precision=9,columnDefinition="NUMBER")
	@XmlElement(name="measureId")
	private Integer measureId;

	@Column(name="BILLING_TYPE",precision=4,columnDefinition="NUMBER")
	@XmlElement(name="billingType")
	private Integer billingType;

	@Column(name="SO_NBR",precision=15,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="soNbr")
	private Long soNbr;

	@Column(name="SO_DATE",columnDefinition="TimeStamp")
	@XmlElement(name="soDate")
	private Date soDate;

	@Column(name="RESOURCE_ID",precision=15,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="resourceId")
	private Long resourceId;

	@Column(name="CREDIT_FLAG",precision=2,columnDefinition="NUMBER")
	@XmlElement(name="creditFlag")
	private Integer creditFlag;

	public void setAssetId(Long obj){
		this.assetId = obj;
	}

	public Long getAssetId(){
		return assetId;
	}

	public void setCreditItem(Integer obj){
		this.creditItem = obj;
	}

	public Integer getCreditItem(){
		return creditItem;
	}

	public void setAcctId(Long obj){
		this.acctId = obj;
	}

	public Long getAcctId(){
		return acctId;
	}

	public void setValidDate(Date obj){
		this.validDate = obj;
	}

	public Date getValidDate(){
		return validDate;
	}

	public void setExpireDate(Date obj){
		this.expireDate = obj;
	}

	public Date getExpireDate(){
		return expireDate;
	}

	public void setCreateDate(Date obj){
		this.createDate = obj;
	}

	public Date getCreateDate(){
		return createDate;
	}

	public void setCreditAmount(Long obj){
		this.creditAmount = obj;
	}

	public Long getCreditAmount(){
		return creditAmount;
	}

	public void setMeasureId(Integer obj){
		this.measureId = obj;
	}

	public Integer getMeasureId(){
		return measureId;
	}

	public void setBillingType(Integer obj){
		this.billingType = obj;
	}

	public Integer getBillingType(){
		return billingType;
	}

	public void setSoNbr(Long obj){
		this.soNbr = obj;
	}

	public Long getSoNbr(){
		return soNbr;
	}

	public void setSoDate(Date obj){
		this.soDate = obj;
	}

	public Date getSoDate(){
		return soDate;
	}

	public void setResourceId(Long obj){
		this.resourceId = obj;
	}

	public Long getResourceId(){
		return resourceId;
	}

	public void setCreditFlag(Integer obj){
		this.creditFlag = obj;
	}

	public Integer getCreditFlag(){
		return creditFlag;
	}

	public CaCredit(){
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CaCredit rhs=(CaCredit)rhs0;
		if(!ObjectUtils.equals(assetId, rhs.assetId)) return false;
		if(!ObjectUtils.equals(creditItem, rhs.creditItem)) return false;
		if(!ObjectUtils.equals(acctId, rhs.acctId)) return false;
		if(!ObjectUtils.equals(validDate, rhs.validDate)) return false;
		if(!ObjectUtils.equals(expireDate, rhs.expireDate)) return false;
		if(!ObjectUtils.equals(createDate, rhs.createDate)) return false;
		if(!ObjectUtils.equals(creditAmount, rhs.creditAmount)) return false;
		if(!ObjectUtils.equals(measureId, rhs.measureId)) return false;
		if(!ObjectUtils.equals(billingType, rhs.billingType)) return false;
		if(!ObjectUtils.equals(soNbr, rhs.soNbr)) return false;
		if(!ObjectUtils.equals(soDate, rhs.soDate)) return false;
		if(!ObjectUtils.equals(resourceId, rhs.resourceId)) return false;
		if(!ObjectUtils.equals(creditFlag, rhs.creditFlag)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(assetId)
		.append(creditItem)
		.append(acctId)
		.append(validDate)
		.append(expireDate)
		.append(createDate)
		.append(creditAmount)
		.append(measureId)
		.append(billingType)
		.append(soNbr)
		.append(soDate)
		.append(resourceId)
		.append(creditFlag)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{assetId,creditItem,acctId,validDate,expireDate,createDate,creditAmount,measureId,billingType,soNbr,soDate,resourceId,creditFlag}
}