package com.ailk.openbilling.persistence.acct.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="AD",name="CA_INTERFACE_BUSI_SPEC_REL")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"interfaceName","methodName","speciId"})
public class CaInterfaceBusiSpecRel extends DataObject{


	@Id
	@Column(name="INTERFACE_NAME",columnDefinition="Varchar",length=256,nullable=false)
	@XmlElement(name="interfaceName")
	private String interfaceName;

	@Id
	@Column(name="METHOD_NAME",columnDefinition="Varchar",length=256,nullable=false)
	@XmlElement(name="methodName")
	private String methodName;

	@Id
	@Column(name="SPECI_ID",precision=8,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="speciId")
	private Integer speciId;

	public void setInterfaceName(String obj){
		this.interfaceName = obj;
	}

	public String getInterfaceName(){
		return interfaceName;
	}

	public void setMethodName(String obj){
		this.methodName = obj;
	}

	public String getMethodName(){
		return methodName;
	}

	public void setSpeciId(Integer obj){
		this.speciId = obj;
	}

	public Integer getSpeciId(){
		return speciId;
	}

	public CaInterfaceBusiSpecRel(){
	}

	public CaInterfaceBusiSpecRel(String interfaceName,String methodName,Integer speciId){
		this.interfaceName = interfaceName;
		this.methodName = methodName;
		this.speciId = speciId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		CaInterfaceBusiSpecRel rhs=(CaInterfaceBusiSpecRel)rhs0;
		if(!ObjectUtils.equals(speciId, rhs.speciId)) return false;
		if(!ObjectUtils.equals(interfaceName, rhs.interfaceName)) return false;
		if(!ObjectUtils.equals(methodName, rhs.methodName)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(speciId)
		.append(interfaceName)
		.append(methodName)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{interfaceName,methodName,speciId}
}