package com.ailk.openbilling.action.imsinner;

import com.ailk.easyframe.web.common.annotation.Param;
import com.ailk.easyframe.web.common.annotation.ParamType;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryThreadInfoResponse;
import com.ailk.openbilling.persistence.imsintf.entity.SOperInfo;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryGroupInfo4GUIResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryGroup4GUIReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryMultiSim4GuiResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryMultiSimReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryUserByOfferNmaeResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryUserByOfferNameReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryBatchUserResponse;
import com.ailk.openbilling.persistence.imsinner.entity.BatchUserWhere;
import com.ailk.openbilling.persistence.imsinner.entity.BatchUserInfo;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryBatchAcctResponse;
import com.ailk.openbilling.persistence.imsinner.entity.BatchAcctWhere;
import com.ailk.openbilling.persistence.imsinner.entity.BatchAccountInfo;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryBatchCustResponse;
import com.ailk.openbilling.persistence.imsinner.entity.BatchCustomerInfo;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryProdListResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryAcctProdListReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_QueryCommonUserInfoResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryUserByIdReq;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryAcctByPhoneReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryFirstBillDaysResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryFirstBillDaysReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryCustomerHistoryForGUIResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryCustomerHistoryReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryVPNGroupResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryVPNGroupReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryBudgetRuleResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryBudgetRuleReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryParentAcctTreesResponse;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryUserListForGuiResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryUserListForGuiReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryUserTargetStsInfoRespons;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryUserTargetStsInfoReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryProdInfoHisResponse;
import com.ailk.openbilling.persistence.imsinner.entity.QueryProdInfoHisReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryBalanceResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryBalanceReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_fuzzyCustsForGUIResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQuerySCustomersReq;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryProductsByUserIdReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryUsersByConditionsResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryUsersReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryProdOfferingInfoResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQryProdOfferInfoReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryAcctsByCustIdResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryAcctInfoReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryOfferingInfoResponse;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryBugetResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryBugetReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_querySplitListResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQuerySplitListReq;
import com.ailk.openbilling.persistence.imsinner.entity.SQuerySplitByUserReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryAcctsForGUIResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryAcctsForGUIReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_QueryCustIdByAcctIdResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryCustIdByAcctIdReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryUsersByAcctIdResponse;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryServiSpecIdsByCustIdResponse;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryAcctTreesByGroupIdResponse;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryProductsByUserIdResponse;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryCustBaseInfoResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryCustBaseInfoReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryServicesByUserIdResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryServicesReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_QueryReguideInfoForGUIResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryReguideInfoReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_QueryAcctByIdResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryAcctByIdReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_QueryUserByIdResponse;
import com.ailk.openbilling.persistence.imsinner.entity.Do_QueryCmResIdentityByDevResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryCmResIdentityByDevReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_QueryAcctByPhoneResponse;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryCustomerInfoResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryCustomerInfoReq;
import com.ailk.openbilling.persistence.imsinner.entity.Do_isPrimaryProductResponse;
import com.ailk.openbilling.persistence.imsinner.entity.Do_queryAccountsSuffixResponse;
import com.ailk.openbilling.persistence.imsinner.entity.SQueryAccountsSuffixReq;
import jef.codegen.support.NotModified;
@NotModified
public interface InnerQueryAction{

	public Do_queryThreadInfoResponse do_queryThreadInfo(@Param("sOper") SOperInfo sOper,@Param("threadId") Long threadId);
	public Do_queryGroupInfo4GUIResponse do_queryGroupInfo4GUI(@Param("sOper") SOperInfo sOper,@Param("sQueryGroup4GUIReq") SQueryGroup4GUIReq sQueryGroup4GUIReq);
	public Do_queryMultiSim4GuiResponse do_queryMultiSim4Gui(@Param("sOper") SOperInfo sOper,@Param("queryMutltSimReq") SQueryMultiSimReq queryMutltSimReq);
	public Do_queryUserByOfferNmaeResponse do_queryUserByOfferName(@Param("sOper") SOperInfo sOper,@Param("req") SQueryUserByOfferNameReq req);
	public Do_queryBatchUserResponse do_queryBatchUserList(@Param("sOperInfo") SOperInfo sOperInfo,@Param("batchUserWhere") BatchUserWhere batchUserWhere,@Param("batchUserInfo") BatchUserInfo batchUserInfo);
	public Do_queryBatchAcctResponse do_queryBatchAcctList(@Param("sOper") SOperInfo sOper,@Param("batchAcctWhere") BatchAcctWhere batchAcctWhere,@Param("batchAcctInfo") BatchAccountInfo batchAcctInfo);
	public Do_queryBatchCustResponse do_queryBatchCustList(@Param("sOper") SOperInfo sOper,@Param("batchCustomerInfo") BatchCustomerInfo batchCustomerInfo);
	public Do_queryProdListResponse do_queryAcctProdList(@Param("sOper") SOperInfo sOper,@Param("sQueryAcctProdListReq") SQueryAcctProdListReq sQueryAcctProdListReq);
	public Do_QueryCommonUserInfoResponse do_queryCommonInfoByUserId(@Param("SOper") SOperInfo SOper,@Param("sQueryUserByIdReq") SQueryUserByIdReq sQueryUserByIdReq);
	public Do_QueryCommonUserInfoResponse do_queryCommonInfoByPhoneId(@Param("SOper") SOperInfo SOper,@Param("sQueryAcctByPhoneReq") SQueryAcctByPhoneReq sQueryAcctByPhoneReq);
	public Do_queryFirstBillDaysResponse do_queryFirstBillDays(@Param("sOper") SOperInfo sOper,@Param("squeryFirstBillDaysReq") SQueryFirstBillDaysReq squeryFirstBillDaysReq);
	public Do_queryCustomerHistoryForGUIResponse do_queryCustomerHistory(@Param("sOper") SOperInfo sOper,@Param("sQueryCustomerHistoryReq") SQueryCustomerHistoryReq sQueryCustomerHistoryReq);
	public Do_queryVPNGroupResponse do_queryVPNGroup(@Param("sOper") SOperInfo sOper,@Param("groupReq") SQueryVPNGroupReq groupReq);
	public Do_queryBudgetRuleResponse do_queryBudgetRule(@Param("sOper") SOperInfo sOper,@Param("budgetRuleReq") SQueryBudgetRuleReq budgetRuleReq);
	public Do_queryParentAcctTreesResponse do_queryParentAcctTrees(@Param("sOper") SOperInfo sOper,@Param("acct_id") Long acct_id);
	public Do_queryUserListForGuiResponse do_queryUserListForGui(@Param("sOper") SOperInfo sOper,@Param("queryUserListReq") SQueryUserListForGuiReq queryUserListReq);
	public Do_queryUserTargetStsInfoRespons do_queryUserTargetStsInfoForGUI(@Param("sOper") SOperInfo sOper,@Param("sQueryUserTargetStsInfoReq") SQueryUserTargetStsInfoReq sQueryUserTargetStsInfoReq);
	public Do_queryProdInfoHisResponse do_queryProdHisInfo(@Param("sOper") SOperInfo sOper,@Param("queryProdInfoHisReq") QueryProdInfoHisReq queryProdInfoHisReq);
	public Do_queryBalanceResponse do_queryBalance(@Param("sOper") SOperInfo sOper,@Param("queryBalanceReq") SQueryBalanceReq queryBalanceReq);
	public Do_fuzzyCustsForGUIResponse do_queryCustomers(@Param("sOper") SOperInfo sOper,@Param("sQueryCustomersReq") SQuerySCustomersReq sQueryCustomersReq);
	public Do_queryProdListResponse do_queryUserProdList(@Param("sOper") SOperInfo sOper,@Param("sQueryProductsByUserIdReq") SQueryProductsByUserIdReq sQueryProductsByUserIdReq);
	public Do_queryUsersByConditionsResponse do_queryUsersByConditions(@Param("sOperInfo") SOperInfo sOperInfo,@Param("SQueryUsersReq") SQueryUsersReq SQueryUsersReq);
	public Do_queryProdOfferingInfoResponse do_queryProdOfferInfo(@Param("sOper") SOperInfo sOper,@Param("sQryProdOfferInfoReq") SQryProdOfferInfoReq sQryProdOfferInfoReq);
	public Do_queryAcctsByCustIdResponse do_queryAcctsByCustId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("req") SQueryAcctInfoReq req);
	public Do_queryOfferingInfoResponse do_queryOfferingInfoByOfferId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("offering_id") Integer offering_id);
	public Do_queryBugetResponse do_queryBuget(@Param("sOperInfo") SOperInfo sOperInfo,@Param("sQueryBugetReq") SQueryBugetReq sQueryBugetReq);
	public Do_querySplitListResponse do_querySplitInfo(@Param("sOperInfo") SOperInfo sOperInfo,@Param("splitListReq") SQuerySplitListReq splitListReq);
	public Do_querySplitListResponse do_querySplitByAcctId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("splitByAcctIdReq") SQuerySplitListReq splitByAcctIdReq);
	public Do_querySplitListResponse do_querySplitByUserId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("splitByUserIdReq") SQuerySplitByUserReq splitByUserIdReq);
	public Do_queryAcctsForGUIResponse do_queryAcctsForGUI(@Param("sOper") SOperInfo sOper,@Param("sQueryAcctsForGUIReq") SQueryAcctsForGUIReq sQueryAcctsForGUIReq);
	public Do_QueryCustIdByAcctIdResponse do_queryCustIdByAcctId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("req") SQueryCustIdByAcctIdReq req);
	public Do_queryUsersByAcctIdResponse do_queryUsersByAcctId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("acct_id") Long acct_id,@Param("relation_type") Integer relation_type);
	public Do_queryServiSpecIdsByCustIdResponse do_queryServiceSpecIdsByCustId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("cust_id") Long cust_id);
	public Do_queryAcctTreesByGroupIdResponse do_queryAcctTreesByGroupId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("acct_id") Long acct_id);
	public Do_queryProductsByUserIdResponse do_queryProductsByUserId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("req") SQueryProductsByUserIdReq req);
	public Do_queryCustBaseInfoResponse do_queryCustBasicInfo(@Param("sOperInfo") SOperInfo sOperInfo,@Param("sQueryCustBasicInfoReq") SQueryCustBaseInfoReq sQueryCustBasicInfoReq);
	public Do_queryServicesByUserIdResponse do_queryServicesByUserId(@Param("sOperInfo") SOperInfo sOperInfo,@Param("seviceReq") SQueryServicesReq seviceReq);
	public Do_QueryReguideInfoForGUIResponse do_queryReguideInfoForGUI(@Param("sOper") SOperInfo sOper,@Param("sQueryReguideInfoReq") SQueryReguideInfoReq sQueryReguideInfoReq);
	public Do_QueryAcctByIdResponse do_queryAcctById(@Param("sOperInfo") SOperInfo sOperInfo,@Param("req") SQueryAcctByIdReq req);
	public Do_QueryUserByIdResponse do_queryUserById(@Param("sOperInfo") SOperInfo sOperInfo,@Param("req") SQueryUserByIdReq req);
	public Do_QueryCmResIdentityByDevResponse do_queryCmResIdentityByDev(@Param("sOperInfo") SOperInfo sOperInfo,@Param("req") SQueryCmResIdentityByDevReq req);
	public Do_QueryAcctByPhoneResponse do_queryAcctInfoByDev(@Param("sOperInfo") SOperInfo sOperInfo,@Param("req") SQueryAcctByPhoneReq req);
	public Do_queryCustomerInfoResponse do_queryCustormInfo(@Param("sOper") SOperInfo sOper,@Param("reqParam") SQueryCustomerInfoReq reqParam);
	public Do_isPrimaryProductResponse do_isPrimaryProduct(@Param("sOper") SOperInfo sOper,@Param("prod_id") Long prod_id);
	public Do_queryAccountsSuffixResponse do_queryAccountsSuffix(@Param("sOper") SOperInfo sOper,@Param("sQueryAccountsSuffixReq") SQueryAccountsSuffixReq sQueryAccountsSuffixReq);

}