package com.ailk.openbilling.persistence.busi.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.GenerationType;
import javax.persistence.GeneratedValue;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAccessType;
import org.apache.commons.lang.ObjectUtils;
import org.apache.commons.lang.builder.HashCodeBuilder;
import jef.codegen.support.NotModified;
/**
 * This class was generated by EasyFrame according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 * 
 */
@NotModified
@Entity
@Table(schema="bd",name="RS_SYS_ELEMENT_CALL_TYPE")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(propOrder={"callTypeId","callTypeName","description"})
public class RsSysElementCallType extends DataObject{


	/**
	 * Call type identification, for identifying different call types
Such as caller, called
	 */
	@GeneratedValue(strategy=GenerationType.SEQUENCE)
	@Id
	@Column(name="CALL_TYPE_ID",precision=10,columnDefinition="NUMBER",nullable=false)
	@XmlElement(name="callTypeId")
	private Integer callTypeId;

	/**
	 * Call type name
	 */
	@Column(name="CALL_TYPE_NAME",columnDefinition="Varchar",length=256)
	@XmlElement(name="callTypeName")
	private String callTypeName;

	/**
	 * description
	 */
	@Column(name="DESCRIPTION",columnDefinition="Varchar",length=1024)
	@XmlElement(name="description")
	private String description;

	public void setCallTypeId(Integer obj){
		this.callTypeId = obj;
	}

	public Integer getCallTypeId(){
		return callTypeId;
	}

	public void setCallTypeName(String obj){
		this.callTypeName = obj;
	}

	public String getCallTypeName(){
		return callTypeName;
	}

	public void setDescription(String obj){
		this.description = obj;
	}

	public String getDescription(){
		return description;
	}

	public RsSysElementCallType(){
	}

	public RsSysElementCallType(Integer callTypeId){
		this.callTypeId = callTypeId;
	}

	public boolean equals(final Object rhs0){
		if (rhs0 == null)return false;
		RsSysElementCallType rhs=(RsSysElementCallType)rhs0;
		if(!ObjectUtils.equals(callTypeId, rhs.callTypeId)) return false;
		return super.isEquals(rhs);
	}

	public int hashCode(){
		return new HashCodeBuilder()
		.append(callTypeId)
		.append(super.getHashCode())
		.toHashCode();
	}


public enum Field implements jef.database.Field{callTypeId,callTypeName,description}
}